### ISSUE TITLE
Unable to import FoldedLightCurve from lightcurve.py

### ISSUE THREAD

**Issue by johnnyzhang295** [KeplerGO/lightkurve#175]
Using ipython 6.2.1, I run the command:

`from lightkurve import FoldedLightCurve`

and I get an ImportError that looks like:
`ImportError
<ipython-input-1-aee3c474c75> in <module>()`
`----> 1 from lightkurve import FoldedLightCurve`
`ImportError: cannot import name 'FoldedLightCurve'`

Same issue also occurs with LightCurveCollection and TargetPixelFileCollection classes.

I think it has something to do with the relative imports?

**Comment by barentsen** [comment]
This is because we use the `__all__` module variable to determine which names get exported from the namespace of a module.  In other words, the solution is to add `FoldedLightCurve` to the `__all__` parameter, here: https://github.com/KeplerGO/lightkurve/blob/master/lightkurve/lightcurve.py#L26

(Same for the collection classes!)

**Comment by barentsen** [comment]
@johnnyzhang295 seems to be happy so I'm closing this!
