### ISSUE TITLE
`lc.remove_outliers()` should support removing positive/negative outliers only

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#221]
Suggestion from @JeffLCoughlin: `lc.remove_outliers()` should have an option to only remove positive outliers, which would enable users to remove cosmic rays (which add flux) whilst preserving planet transits (which reduce flux).

**Comment by JeffLCoughlin** [comment]
Thanks for opening. Science case example is users will likely want to remove outliers due to cosmic rays without clipping out data from transits. I suggest options for remove_outliers(), such as:

- Remove positive/negative outliers only.
- Set custom sigma value for positive and negative separately.

Side note: I have a phased-light-curve outlier rejection scheme I built into modshift that might be useful to port one day. Works quite well to reject outliers and preserve repeating astrophysical signals if you have a known period.

**Comment by barentsen** [comment]
@anand-sundaram-zocdoc Thank you for looking into this!

Good point!!  I didn't think to check astropy's `sigma_clip` function to check if it isn't already supported.  It is!  In this case, we'll only need a PR to update the docstring of `remove_outliers()` to mention these useful parameters and provide an example.

=> i.e. I think we should list and explain `sigma_lower` and `sigma_upper` as parameters in the `Parameters` section of the docstring, and add an `Examples` section to the docstring that demonstrates their use.

@anand-sundaram-zocdoc If you are interested in contributing to Lightkurve, the above docstring update would be valuable and likely to get merged easily!

**Comment by barentsen** [comment]
Thanks to #276, `remove_outliers()` now explicitly support `sigma_lower` and `sigma_upper` arguments.  This issue has been resolved!
