### ISSUE TITLE
BUG REPORT: Problems with KeplerLightCurveFile.from_archive method.

### ISSUE THREAD

**Issue by KenMighell** [KeplerGO/lightkurve#254]
#### Problem description
lightkurve sometimes fails to retrieve existing short-cadence light
curve files from MAST using the lk.KeplerLightCurveFile.from_archive method.

#### Example

```python
import lightkurve as lk
targets = [212803289, 206003187, 206019387]
campaigns = [17, 3, 3]
cadence = 'short'
for target,campaign in zip(targets,campaigns):
    print
    print '=============================='
    print target,'=target'
    print campaign,'=campaign'
    print cadence,'=cadence'
    print 'slcf:',
    try:
        slcf = lk.KeplerLightCurveFile.from_archive(target=target,\
          campaign=campaign,cadence=cadence)
        print 'OK'
        print slcf.path
    except:
        print '*** ERROR ***'
```

For the last 2 targets MAST reports:

**Target return limit set to 1 but only 0 unique targets found. Try increasing the search radius. (Radius currently set to 1.0 arcseconds)**

The last two short-cadence light curve files do exist at MAST:

https://archive.stsci.edu/missions/k2/lightcurves/c3/206000000/03000/ktwo206003187-c03_slc.fits

https://archive.stsci.edu/missions/k2/lightcurves/c3/206000000/19000/ktwo206019387-c03_slc.fits

#### Expected behavior
This code snippet should retrieve 3 existing short-cadence light curve files from MAST
without any problems.

#### Environment:
- platform: OSX
- lightkurve version: 1.0b15
- installation method: pip install lightkurve --upgrade

#### Question:
Why does lightkurve sometimes fail to retrieve existing short-cadence light
curve files from MAST using the lk.KeplerLightCurveFile.from_archive method?

-Ken Mighell

P.S. I have a Jupyter notebook that shows the problem.  But I can not attach it to this
bug report.

**Comment by barentsen** [comment]
Ken: well-spotted, thank you!

Short-cadence lightcurves for C3 were first added to the archive 1-2 weeks ago as part of the C3R re-delivery (because the original C3 processing did not produce short cadence lightcurves).  It often takes 1-2 weeks for those new files to show up in the MAST API.

@scfleming @mustaric Am I correct to assume that C3R is not in the portal API just yet, or should we investigate this issue in more detail?

**Comment by scfleming** [comment]
Thanks for reporting, this work was in testing and I think got delayed longer than expected due to some issues we found on our end, so I don't think the C3 short cadence are in the operational Portal quite yet, but I've inquired about how much longer testing will take.  I'll follow up as soon as I know more, and apologies for the delay!

**Comment by barentsen** [comment]
@scfleming No worries, this isn't critical! Thanks for the update. I'm happy it's not a bug =)
