### ISSUE TITLE
How to save custom aperture masks?

### ISSUE THREAD

**Issue by gully** [KeplerGO/lightkurve#264]
Imagine you painstakingly create a custom aperture mask for aperture photometry.  Perhaps you've done so with our slick new `.interact()` method.  Or maybe you've done so programmatically by some other means that may be difficult to reproduce.  What are your options for saving your work?

Chiefly, the options come down to:  

0. Do nothing--- leave it up to the user to save masks with their desired format (status quo)
1. Save just the mask (in some format-to-be-named-later)
2. Save the lightcurve with *e.g.* the `.to_fits()` method with an HDU extension for the mask
3. Save a new target pixel file with a new HDU extension for the mask

**Comment by JeffLCoughlin** [comment]
I think option 2 would be great. Right now for our TPF files HDU extension #2 (the third and final extension) is the pipeline aperture. Adding additional apertures as extension #3, #4, #5, etc. seems natural and convenient. Their format could mimic the existing #2 format.

I believe this would allow the file to be used normally by any software, as the first 3 extensions remain untouched.

**Comment by lacalaca85** [comment]
I second Jeff, No 2 sounds great. Light curve is readily reproducible with the stored custom mask. We struggled with this in pyke where overwriting the mask files was rather easy... 
And we will be able read back the mask from the light curve file onto the original TPF, right?

**Comment by barentsen** [comment]
I'd be fine with #2!  Who would like to volunteer to try and implement it?

**Comment by gully** [comment]
It looks like option 2 wins based on unanimous feedback so far: 3/3 votes.  So then the question becomes implementation, what needs to change in order to "save the lightcurve with e.g. the .to_fits() method with an HDU extension for the mask":

The `.to_fits()` method currently works on LightCurve objects, which presently have no way to know what mask generated them.  It seems to me that there are a few design and practical considerations for moving forward:

1. Modify `to_fits()` to support HDU mask extensions, and/or verify that it's possible and robust.  Do we want to mimic extant formats from, e.g. K2SFF/EVEREST/Kepler Pipeline?
2. Modify LightCurve or its subclasses to support a `.mask_that_generated_this_lightcurve` property (or a more-concise-attribute-name-to-be-decided-upon-later), which could get seamlessly passed to `to_fits()`).  This attribute may not be desirable or may not be possible to support.
3. Decide on the `interact()` user experience: click a button to save? Pass a kwarg-- `interact(export_lightcurve=True)` ? Do we want invisible/automatic triggering upon a Kwarg?
4. Decide on how to name the file-- do default names come from the metadata of the TPF?  What if multiple versions are exported?  Do we want to encode metadata about the mask in the filename?
5. Decide on whether/how to return the mask as a local variable, or force a save-and-read-in strategy?

**Comment by gully** [comment]
By the way, I think @KenMighell and @christinahedges had verbally expressed interest in Option 3, "Save a new target pixel file with a new HDU extension for the mask".  If you still like option 3, please chime in here soon to extoll its virtues.

**Comment by barentsen** [comment]
We should discuss, but my two cents:
* I'm fine for `LightCurve` to have an optional `aperture_mask` attribute that gets written to its own extension by `LightCurve.to_fits()`.  Although it deviates from the pipeline format, the mask really is an attribute that is associated with a LightCurve rather than a TargetPixelFile. The extension should use the same format as that used to save a mask in a TargetPixelFile however.
* The `interact()` tool can have a simple `save` button which will call `LightCurve.to_fits()` using some default filename.  If a different filename is desired, it will have to be passed when starting interact, e.g. `interact(output_filename=x)` or similar.

Because interact runs in an asynchronous way (i.e. the tool still works after the method returns), I can't think of a good way to return the mask as a variable.  Accessing the mask by opening the FITS file created seems fine!

**Comment by gully** [comment]
> The extension should use the same format as that used to save a mask in a TargetPixelFile however

I propose a simple binary mask: `1` for in the mask, `0` for out of the mask.

**Comment by barentsen** [comment]
Below I copy/paste the exact specification from the [Kepler archive manual](https://archive.stsci.edu/kepler/manuals/archive_manual.pdf) and the [TESS documentation](https://archive.stsci.edu/missions/tess/doc/EXP-TESS-ARC-ICD-TM-0014.pdf).  They are different but they both give the same meaning to bits 1 and 2, so I think we may want to stick to those!

![screenshot from 2018-11-08 10-07-41](https://user-images.githubusercontent.com/817669/48218187-29966600-e33e-11e8-9603-dd15058f9fd8.png)


![screenshot from 2018-11-08 10-05-14](https://user-images.githubusercontent.com/817669/48218057-d58b8180-e33d-11e8-8d96-b27a6314fa60.png)

**Comment by gully** [comment]
See some discussion at #329 that relates to discussion here.  There does not presently exist a convenient way to "round trip": 

`LightCurve`  ➡️  fits file ➡️ `LightCurve`

...while preserving metadata.  Issue #289 is essentially the solution to the round trip problem--- we need support for reading in non-mission-produced lightcurves (e.g. HLSPs and these custom interact-produced lightcurves).

**Comment by gully** [comment]
> They are different but they both give the same meaning to bits 1 and 2, so I think we may want to stick to those!

I will do the following per guidance above:

### Our approach
Use `0` to indicate that the pixel was not telemetered by the spacecraft (e.g. all-NaN data... will require an additional cross-match with the original HDU, since we do not presently make this distinction.)
Use `1` to indicate that the pixel was telemetered by the spacecraft.
Use `2` to indicate that the pixel was in the *custom* (e.g. `interact()`-generated) aperture mask.

### Common approach
Use `0` to indicate that the pixel was not in the custom mask
Use `1` to indicate that the pixel was in the custom mask

### Note on prospects for confusion
A user could erroneously assume numpy-style boolean masking, the standard format adopted by K2SFF and our in-house methods (anything that accepts `aperture_mask=` expects a boolean mask, AFAIK).  User-generated `to_fits()` masks are unlikely to share our convention, so lightkurve-generated fits files will likely have discordant mask conventions.  

With that said, I think users are generally comfortable with the notion that products from the Mission have one format, and products from the community have other formats, so it's probably no big deal.  I'm mostly noting these potential pitfalls here in case someone encounters them later and wonders which convention-is-used-when-and-where-and-why.

**Comment by barentsen** [comment]
The inconsistency with the boolean `aperture_mask` convention used elsewhere in Lightkurve is a fair reason for concern.  I wonder if we should alter the `_parse_aperture_mask()` method in `TargetPixelFile` to accept both boolean masks and integer-based masks, e.g.:

```
if aperture_mask.dtype == bool:
    mask = aperture_mask
else:
    mask = aperture_mask & 2
```
...plus some error-checking to warn the user if they accidentally used an integer mask that contains only zeros and ones. Thoughts?

**Comment by gully** [comment]
Maybe? I'll get some practical experience and make some tests to probe these scenarios as part of the present interrelated pull requests.

**Comment by christinahedges** [comment]
@gully, @nksaunders and I have had a chat about this.

We've weighed up the options from @gully's first post:

> 0. Do nothing--- leave it up to the user to save masks with their desired format (status quo)
> 1. Save just the mask (in some format-to-be-named-later)
> 2. Save the lightcurve with e.g. the .to_fits() method with an HDU extension for the mask
> 3. Save a new target pixel file with a new HDU extension for the mask

Some take aways from our discussion

### Option 1. Save just the mask

Masks would be fits files with keywords describing the way they were generated and the file they apply to. 

#### Pros: 
- Small file size
- No change to lightkurve infrastructure needed.

#### Cons:
- Have to carry around mask and TPF to use.
- Have to include a way to read in masks in lightkurve (i.e. `tpf.to_lightcurve(aperture_mask=parse_mask('mask.fits'))`)
- Masks could be applied to the wrong file.


### Option 2. Save a fits file with a light curve and an aperture extension

#### Pros:
- Small file size
- Easy to reproduce/share with collaborators
- No intermediate steps
- Will work for TESS regardless of postage stamp/tpf/two minute cadence etc
- Potentially adds infrastructure for use when loading in HLSPs.

#### Cons:
- Not inherently reproducible. To reproduce the light curve contained in the fits file you would also need the TPF.
- Requires a new attribute `aperture_mask` in all `LightCurve`, which is populated or produces a descriptive warning in all subclasses. This is a fairly large change to a major class in lightkurve.
- The `aperture_mask` attribute must be writeable in the `LightCurve.to_fits()`
- Custom light curves fits files from `tpf.interact` will not behave like Light Curve Files. They must still be readable by lightkurve, into `KeplerLightCurve` objects (or `TESSLightCurve` objects). This is new behavior which needs to be written and unit tested.

### Watch out for:
- Need to ensure that the fits file generated by `tpf.interact()` has no  information loss compared with the equivalent `lcf.SAP_FLUX()` object.

- Have to ensure that the fits file generated by the `tpf.interact()` button can be read back into lightkurve. (i.e. `lk.open('custom_lc_file.fits')` must produce the same object with the same attributes as the equivalent `lcf.SAP_FLUX()` object.) Gully refers to this as round tripping above. This is necessary for this button to really be useful. If we include this button in lightkurve v1.0, this issue must be addressed. 

- `lk.open('custom_lc_file.fits')` must return a `KeplerLightCurve` or `TESSLightCurve` class, not a generic `LightCurve` class. (Otherwise information has been lost.)

- This option will require that the KeplerLightCurve returned by `lk.open('custom_lc_file.fits')` will have a new attribute `aperture_mask`. This requires changing the base class `LightCurve` to have a blank `aperture_mask` attribute that will be able to be set. When the attribute is accessed from different objects it should always provide a reasonable result, see below. **All of these scenarios must be unit tested**

``` python

tpf = open('targetpixelfile.fits')
tpf.aperture_mask     # equivalent to tpf.pipeline_mask

lc = tpf.to_lightcurve()
lc.aperture_mask      # provides pipeline aperture

lcf = open('lightcurvefile.fits')
lcf.aperture_mask   # MUST either produce a useful warning/exception, or fetch the aperture mask
lcf.SAP_FLUX.aperture_mask   # MUST either produce a useful warning/exception, or fetch the aperture mask

lcf.SAP_FLUX.to_fits('my_hlsp_file.fits')
my_hlsp_lc = open('my_hlsp_file.fits')
my_hlsp_lc.aperture_mask   # Has no aperture extension?

lc = open('custom_light_curve.fits')
lc.aperture_mask     # provides pipeline aperture
lc.to_fits('my_custom_file.fits')
my_custom_lc = open('my_custom_file.fits')
my_custom_lc.aperture_mask   # Does have an aperture extension?

```

### Option 3. Save a new target pixel file with a new HDU extension for the mask

#### Pros:
- Provides all the information for reproducible light curves, can share a single file with collaborators.
- Requires no infrastructure change for lightkurve.

#### Cons:
- Large file size, irresponsible to fill up users hard drives
- Inconvenient for power users, who only want the aperture mask.

### Some decisions

@gully has made lots of headway on option 2 in PR #329. I'm writing my concerns about option two in detail here. I find option 1 to probably on balance be the most palatable, although I don't love the idea of lots of dangling mask files that I'm easily going to lose.

If all my concerns under option 2 can be addressed then it is the best solution. However, it looks like quite a bit of work, especially before we release v1.0.

**Comment by gully** [comment]
Thank you Christina for your thinking on this issue.

I've been confused on which-data-products-have-which masks, so I compiled some info to help guide the discussion.

The table below summarizes mask properties for existing data products.

The columns show the data products, their equivalent lightkurve object, how masks are stored, the provenance of the mask, what type of mask they are, and how to access those masks programmatically with lightkurve.

### Existing data product files

|Data product| lightkurve object| Mask storage| Mask provenance | Mask type| lightkurve mask access|
| -- | -- | -- | -- | -- |
| Kepler Target Pixel File| `KeplerTargetPixelFile` | HDU ext. 2 "APERTURE" | mission| 4-bit optimal, centroid | `tpf.pipeline_mask` |
| TESS Target Pixel File| `TessTargetPixelFile` | HDU ext. 2 "APERTURE" | mission| 9-bit optimal, bkg, centroid, detector| `tpf.pipeline_mask` |
| Kepler Lightcurve File| `KeplerLightCurveFile` | HDU ext. 2 "APERTURE" | mission | 4-bit optimal, centroid| `(lcf.hdu[2].data & 2) == 2` |
| Tess Lightcurve File| `TessLightCurveFile` | HDU ext. 2 "APERTURE" | mission | 9-bit optimal, bkg, centroid, detector| `(lcf.hdu[2].data & 2) == 2` |
| K2SFF HLSP | *not implemented* | HDU ext. 22, 23 "CIRC_APER_TBL", "PRF_APER_TBL" | Vanderburg & Johnson | binary image cube | *not implemented*|
| EVEREST HLSP | *not implemented* | HDU ext. 3 "APERTURE MASK" | Luger et al. | binary image | *not implemented*|

**Comment by KenMighell** [comment]
I still favor Option #3 (Save a new target pixel file with a new HDU extension for the mask).

The advantage of requiring no infrastructure change for lightkurve is important.  

I have sent a notebook to Gavin Ramsay showing how to improve his K2 analysis of the dwarf 
nova AK Cnc by (1) customizing the aperture and (2) reducing the size of the TPF to have less
than 30000 cadences.  The notebook showed how to do this by hand:

===== snip =====

stpf = lk.KeplerTargetPixelFile.from_archive(target=211378904,campaign=18,cadence='short',\
quality_bitmask=0)

mask = stpf.pipeline_mask
mask[0,5:9] = True
mask[1,5:9] = True
mask[2,4:9] = True
mask[3,3:9] = True
mask[4,2:9] = True
mask[5,2:9] = True
mask[6,2:8] = True
mask[7,3:7] = True
mask[8,4:7] = True

hdul = fits.open(stpf.path)

hdul[1].data = hdul[1].data[5000:20000]

mymask = np.zeros(ltpf.pipeline_mask.shape,dtype=np.int32)
mymask[mask] = 3
mymask[~mask] = 1
hdul[2].data = mymask.copy()  # new aperture mask

filename = 'ktwo211378904-c18_spd-targ_small.fits'
hdul.writeto(filename,overwrite=True)
hdul.close()

===== snip =====

One can then open the new TPF, print the new pipeline mask, plot the lightcurve, and use interact():

===== snip =====

stpf2 = lk.KeplerTargetPixelFile(filename,quality_bitmask=0)

print stpf2.pipeline_mask

stpf2.to_lightcurve()

stpf2.interact()

===== snip =====

lightcurve  is quite happy working with the new hacked short-cadence TPF --- it does not
know that it is not a standard K2 data product.

Allowing interact() to write a new TPF with a new mask in the second extension 
[e.g., hdul[2].data = mymask.copy()  # new aperture mask] allows lightkurve
to be used normally.  To the user this would appear to be an easy and simple operation.

**Comment by gully** [comment]
After much discussion, we are going to implement a way to save masks as the final HDU extension with the first data-holding extension possessing the affiliated custom aperture photometry lightcurve.  We agreed to store the mask as a bitmask with bits 1,2,3,4 yielding values in the set [0, 15], which is the Kepler pipeline standard.  

The meaning of the bits in this bitmask will depart slightly from the Kepler pipeline standard.  The meaning of bit 2 will become "pixel was part of the **custom** aperture" rather than the so-called "optimal" aperture.  Bits 3 and 4 (values 4 and 8) will likely be ignored under most use cases.  Bit 1 signifies whether the pixel was telemetered (conveying whether its inclusion/or exclusion in the custom mask was possible).  Bit 1 might be preserved depending on the application.  

Reading-in the mask will require the *bitwise and* operator in the same way as can be done for KeplerLightCurveFile hdu extensions.  In python:

```python
aperture_mask = (bit_mask & 2) == 2
```

**Comment by gully** [comment]
*n.b.* The TESS bitmask standard equals the Kepler standard, if you ignore bits greater than 4, but I have setup `to_fits()` separately for TESSLightCurves and KeplerLightCurves, just in case someone wants to make some custom bitmasking for TESS.
