### ISSUE TITLE
Allow fancy indexing of KeplerTargetPixelFiles

### ISSUE THREAD

**Issue by KenMighell** [KeplerGO/lightkurve#267]
#### Problem description

lightkurve does not allow fancy indexing of KeplerTargetPixelFiles.

#### Example

```python
import lightkurve as lk
filename = 'ktwo212803289-c17_lpd-targ.fits'
tpf = lk.KeplerTargetPixelFile(filename,quality_bitmask=0)
print type(tpf),'=type(tpf)'
print tpf.shape,'=tpf.shape'
tpf2 = tpf[:1000,:,:]  # try get first 1000 cadences
```
#### Result:

<class 'lightkurve.targetpixelfile.KeplerTargetPixelFile'> =type(tpf)
(3283, 13, 13) =tpf.shape

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-750f9279caf5> in <module>()
      4 print type(tpf),'=type(tpf)'
      5 print tpf.shape,'=tpf.shape'
----> 6 tpf2 = tpf[:1000,:,:]  # get first 1000 cadences

TypeError: 'KeplerTargetPixelFile' object has no attribute '__getitem__'

#### Expected behavior

A smaller tpf object with just the first 1000 cadences.

#### Comment

If full fancy indexing with all three dimensions (cadence,x,y) is not practical, then have a select()
method which would allow the fancy indexing (selection) of cadences alone (leave the x and y
dimensions the same).

#### Environment:
- platform: Mac OS X
- lightkurve version: 1.0b15
- installation method: pip

**Comment by JeffLCoughlin** [comment]
If there is a function to select a subset of cadences from a TPF or lightcurve file,  I think it might also resolve the current interact() limitation of not running on short-cadence due to so many cadences.

Seems like it would be useful in general to not have to 'lug' around a bunch of extra cadences if there are ones for sure you know you want to just get rid of due to their flags or being in a certain time range.

**Comment by barentsen** [comment]
Currently the `KeplerTargetPixelFile` class is a lightweight wrapper around a FITS file on disk, i.e. around an astropy `HDUList` object.  Allowing slicing and masking of such an object would require us to implement a more comprehensive class which models a TPF, so I expect this will be a longer-term project.

For the time being, if you only cared about the flux values, the user could use`tpf.flux[:1000,:,:]` instead of `tpf[:1000,:,:]`.
