### ISSUE TITLE
The Lightkurve repository is more than 200 MB in size

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#371]
This repository is now more than 1 GB in size, which is surprising given the very small number of images and data files it contains.

The git history likely contains accidental commits of large files.  We should look into editing the history, if possible, to avoid burdening new developers with a 1 GB download.

Any volunteers?

**Comment by texadactyl** [comment]
Some folks on github use this: https://rtyley.github.io/bfg-repo-cleaner/
Clone/mirror after everyone agrees to stay out of repo and gets rid of old clones.

**Comment by gully** [comment]
I spot-checked the largest files in the repo.  A bunch of them are `.ipynb_checkpoints`, including some ipynb files that were never committed in master or elsewhere.  I tracked them down to being in the gh-pages branch.  What's happening is that the make html and make notebooks for the documentation are finding any jupyter notebooks and uploading them, which is a major fail and liability, much less bloating our repo.

My recommendation is two fold:

1. Completely rebase the gh-pages branch to squash all commits into one.  
This force push shouldn't be too big of a deal, since the content is independent from master anyways.  The only conceivable pitfall would be whether documentation packaged for older versions gets demolished.  I think the answer there is "no"-- docs only looks for the most recent version anyways (we don't index old docs, as astropy does for example, though maybe we should moving forward?).

2. Understand where the Makefile is going wrong and update it to avoid committing all ipynb's
For example, there might be ghp-import arguments that can help, or maybe a git ls-files trick.

**Comment by gully** [comment]
OK, I force-pushed the gh-pages branch with the last 5 commits squashed, along with a recent commit that removed the content.  I recommend we eventually squash commits going back to when this problem first arose.

**Comment by barentsen** [comment]
Thanks @gully, it looks good!  Before running `make upload`, other developers will want to sync the gh-pages branch as follows:
```
git checkout gh-pages
git fetch
git reset origin/gh-pages --hard
```
(assuming `origin` points to KeplerGO, of course!)

**Comment by barentsen** [comment]
It looks like @gully's intervention dropped the size of the repo to 55 MB, so I think we can close this issue!

I think it's a great idea to have `make upload` be smarter about what it uploads to `gh-pages`, but let's start a new issue for that!
