### ISSUE TITLE
binary aperture_masks of dtype float do not work

### ISSUE THREAD

**Issue by gully** [KeplerGO/lightkurve#395]
#### Problem description
binary aperture_masks of dtype float do not work

#### Example

*works*:

```python
import numpy as np
aper = np.zeros(tpf.shape[1:], dtype=np.int)
aper[-2:, 0:2] = 1
tpf.plot(aperture_mask=aper, mask_color='red');
```

*Doesn't work:*
```python
import numpy as np
aper = np.zeros(tpf.shape[1:], dtype=np.float)
aper[-2:, 0:2] = 1
tpf.plot(aperture_mask=aper, mask_color='red');
```

yields:
```python
--> 410             elif ((aperture_mask & 2) == 2).any(): # Kepler-pipeline style
    411                 aperture_mask = (aperture_mask & 2) == 2
    412         self._last_aperture_mask = aperture_mask

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

#### Expected behavior
Float and int masks of 1.0's and 0.0's should work as binary masks.

#### Environment:
OSX, master version

**Comment by barentsen** [comment]
Although we should discourage users from specifying aperture masks using floats (because the official data products uses integers), I'd be OK with preventing the above crash for ease of use.

I think `TargetPixelFile._parse_aperture_mask()` could including the following logic:
```
# pseudo code
if aperture_mask is of type float:
     warnings.warn('Converting aperture mask from float to int.', LightkurveWarning)
     aperture_mask = aperture_mask.astype(int)
```

@gully do you want to go ahead and open a PR that does the above?  I'd also encourage you to update the docstring of `aperture_mask` to clarify what the valid ways are to specify a mask.  (Note: multiple functions accept `aperture_mask` and all should have the same/consistent docstring for this parameter.)

Thanks++ for spotting this. :+1:

**Comment by barentsen** [comment]
The example posted in the original post appears to work in the current version of Lightkurve, so I think we can close this issue! :+1:
