### ISSUE TITLE
`search_targetpixelfile` does not support FFI cutouts

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#402]
#### Problem description

TESS Search isn't finding my target.
#### Example

```python
import lightkurve
lk.search_targetpixelfile('TIC 206669860')
```

![image](https://user-images.githubusercontent.com/14965634/51947541-201b1800-23da-11e9-8c9d-021355feae37.png)

It is available on MAST

![image](https://user-images.githubusercontent.com/14965634/51947561-28735300-23da-11e9-8a7f-ed7740fd925d.png)

#### Expected behavior

It should find the target. 

#### Environment:
- platform (e.g. Linux, OSX, Windows): OSX
- lightkurve version (e.g. 1.0b6): 1.0b26.dev
- installation method (e.g. pip, conda, source): source

**Comment by nksaunders** [comment]
I was able to reproduce this issue. I did find the expected file with the following snippet:

```python
from lightkurve.search import _query_mast
_query_mast('TIC 206669860')
```

This returns a table containing an observation of the target. However, the identified file is an FFI, which is not currently supported by `lightkurve.search`. 

**Solution**: 
We need to make targets on FFIs accessible through the `search` API. We could adapt the search functions to return FFIs, but we need a way to download them into `lightkurve`-friendly objects. 

Options:
- An interface with TESScut to download the desired pixels
- A new `lightkurve` object to hold FFIs

I can open a PR to address one or both of the above solutions. @christinahedges @barentsen @gully thoughts?

**Comment by barentsen** [comment]
Just documenting here that this is not a bug.  The target was not observed in TESS 2-minute cadence mode.  As a result, the TESS mission did not produce a Target Pixel File for this target and `search_targetpixelfile` did not return a result.  This is the expected behavior at this time.

I do like the idea of having `search_targetpixelfile` return FFI entries in its `SearchResult`.  If the `download()` method was called on such an entry, it could automatically call the TESSCut service and deliver a TPF.
