### ISSUE TITLE
lightkurve should cache its SearchResult object

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#461]
I think lightkurve should somehow cache the SearchResult object, so that if MAST goes down (as it frequently does) or if I'm coding on a plane (as I frequently am) if I run my `lk.search_lightcurvefile('NAME')` it still gives me the same result, and `.download()` will just fetch the path to the cached file.

This is quite a difficult feature to add, but I think it should be possible.

**Comment by orionlee** [comment]
If the goal is to just get lightcurve files, one option is to provide a new method, say, `download_lightcurvefiles()`, which will do:
1. the search and download
2. cache the _part of SearchResult_, so that if the same search is done again, it can fetch the local downloaded files.

Such an approach avoids caching the whole SearchResult objects.

A prototype is available at:  https://github.com/orionlee/PH_TESS_I_LightCurveViewer/blob/master/lightkurve_ext.py

If there are interests, I could possibly generalize and integrate it to proper `lightkurve` package.

**Comment by barentsen** [comment]
@orionlee Thank you for posting the example!! :+1::+1::+1:

Do you think we should avoid caching the entire `SearchResult` object at all cost?  A pickled+compressed `SearchResult` only seems to be a few kilobytes large for a Kepler target, and we can probably cut this in half by removing unnecessary columns from the `SearchResult.table` object.

The advantage of caching the entire `SearchResult` is that we wouldn't have to introduce a new function, we'd simply modify `search_lightcurvefile` to return a cached object if the same query was executed recently.

Example of saving a `SearchResult` on disk to show file size:
```python
In [1]: import lightkurve as lk; import bz2; import pickle                      

In [2]: sr = lk.search_lightcurvefile("Kepler-10")                              

In [3]: len(sr)  # How many files did we find?                                            
Out[3]: 16

In [4]: with bz2.BZ2File('demo.bz2', 'w') as f: 
   ...:     pickle.dump(sr, f) 

In [5]: !ls -lh demo.bz2    # How large is the object on disk?                                                   
-rw-r--r-- 1 gb gb 5.6K Oct 20 20:01 demo.bz2

In [6]: sr.table.columns    # We can probably remove some of these columns from the object
Out[6]: <TableColumns names=('obsID','obs_collection','dataproduct_type','obs_id',
'description','type','dataURI','productType','productGroupDescription','productSubGroupDescription',
'productDocumentationURL','project','prvversion','proposal_id','productFilename','size','parent_obsid',
'dataRights','dataproduct_type_2','calib_level','obs_collection_2','target_name','s_ra','s_dec','t_min',
't_max','t_exptime','wavelength_region','filters','em_min','em_max','target_classification','obs_title',
't_obs_release','instrument_name','proposal_pi','proposal_id_2','proposal_type','project_2',
'sequence_number','provenance_name','s_region','jpegURL','dataURL','dataRights_2','mtFlag',
'srcDen','intentType','obsid','objID','objID1','distance')>
```

**Comment by orionlee** [comment]
Size of `SerachResult` is not too important: they are negligible comparing to the dataset anyway.

I'm more worried about how to save / serialize `SerachResult` correctly and in a maintainable fashion: if it can be done, I do agree that a better approach is to support caching in `search` methods.

My concerns of serializing `SearchResult`: `SerachResult` is largely a wrapper of the underlying astropy mast query result. If the underlying astropy data structure (`astropy` `Table`) changes, what will happen if we read the serialized result from an older version with a newer version of the astropy? 
If it raises an exception, it's okay (just treating it as a cache miss). I'm more worried if it might get read successfully but incorrectly in some edge cases.

---
I looked into it a bit more, and believe there is a way to address my above concern. `Lightkurve` could use `astropy.Table` 's [read/write functions](https://docs.astropy.org/en/stable/table/io.html) to serialize the result. E.g.,

```python
search_res = lk.search.search_lightcurvefile("TOI150")
# use fits for now, the appropriate file format is TBD
search_res.table.write('data/temp.fits', serialize_method='data_mask', overwrite=True)

# load result from disk
tab_l = astropy.table.Table.read('data/temp.fits')
search_res_from_disk = lk.search.SearchResult(tab_l)
```
In this way, the actual serialization logic is maintained by astropy, and would be resilient to any of their changes. It should also be safer than pickle, which could arguably pose some security risk, given pickle could potentially load codes.

**Comment by barentsen** [comment]
Thanks for posting your thoughts.  I agree with what you wrote!

Although I don't *think* we'd run into any serious security or dependency problems with `pickle`, it is certainly *possible* for weird stuff to happen because using `pickle` is far more complicated than simply writing an AstroPy `Table` to disk.  So, I'm fully on board with simply saving the `Table` instead of using `pickle`!

Some additional thoughts on the implementation:
* We'll want to store the time of the original search query in the `Table.meta` dictionary.  If the search result is older than one week (?), we'll want to ignore the cache.
* We'll also want to store the value of `lightkurve.__version__`.  If the cached result was created using a different version, we should probably ignore it.
* We'll probably want a convenient `lightkurve.search.delete_cache()` function which deletes all files stored in the cache, or which deletes all outdated files stored in the cache.

Finally, one outstanding question is whether this belongs inside Lightkurve, or whether we should try to add caching to the underlying astroquery function (i.e. `astroquery.mast.Observations.query_criteria()`).  /cc @ceb8

**Comment by orionlee** [comment]
It looks like `astroquery.mast` deliberately chooses not to allow caching, ignoring the underlying caching support in general astroquery.

https://github.com/astropy/astroquery/blob/v0.3.10/astroquery/mast/core.py#L452

I am not familiar with MAST enough to understand the reason. If the reason does remain valid, it clashes with the offline use case in this issue, or a similar use case of in an interactive notebook, an user might want to (temporarily) cache the MAST response to speed up while tweaking the notebook.

**Comment by ceb8** [comment]
@barentsen @orionlee  The current situation wrt cacheing in astroquery.mast is that we cache the download functions but not any of the queries.  The reason the MAST server queries do not us the astroquery caching functionality is that it clashes with the long polling nature of the MAST servers, meaning that often a result with status "EXECUTING" is returned, and if astroquery caching is turned on it will catch any subsequent queries and return that same "EXECUTING" result, and you can never get the actual result because it required the query to actually reach the MAST servers again.

**Comment by ceb8** [comment]
@barentsen I think it could be worth it, consideration would have to be given to the lifetime of the cache, given that the results of queries will not necessarily be static over time. Realistically I am not going to have the bandwidth to write something like this anytime soon though.

**Comment by barentsen** [comment]
Agreed that the lifetime of the cache would definitely have to be set/configured/checked!

We may have a look into it, time-permitting.

**Comment by orionlee** [comment]
I could possibly take a stab at it, but I will need to first look a bit more at astroquery to see if it's something I can commit to and get back to you.

**Comment by barentsen** [comment]
@orionlee Sounds good! :+1:

**Comment by barentsen** [comment]
I am going to close this issue for now because the caching of search results is being implemented as an `astroquery` feature, most notably here: https://github.com/astropy/astroquery/pull/1634

Depending on how this feature will be implemented inside astroquery, we may or may not have to open a new issue to add support for it inside Lightkurve.

Footnote: as of Lightkurve v1.9.1 the speed of search operations has been increased ten-fold, so anyone who finds this issue because their search operations are slow may want to upgrade to >1.9.1!
