### ISSUE TITLE
TESScut download slow when running a second time

### ISSUE THREAD

**Issue by tfetherolf** [KeplerGO/lightkurve#474]
#### Problem description

I have a script that searches and downloads a long list of TICs using lightkurve TESScut, then I perform various post processing. I expect this to be slow the first time due to the downloading of the light curves and pixel files, but the second time I run the script I expect it to run significantly faster since the files have already been downloaded.

#### Example

```python
import lightkurve as lk
import time

t = time.time()
tcut = lk.search_tesscut('TIC149971754', sector=2)
print "Search time:", time.time()-t
t = time.time()
tcut.download()
print "Download time:", time.time()-t

# Make some code edits, then rerun. 

t = time.time()
tcut = lk.search_tesscut('TIC149971754', sector=2)
print "Search time:", time.time()-t
t = time.time()
tcut.download()
print "Download time:", time.time()-t
```

#### Environment:
- platform: macOS Mojave 10.14.3
- python: 2.7.15
- lightkurve version: 1.0b29

**Comment by barentsen** [comment]
Thank you for reporting this @tfetherolf! :+1:

It is true that `search_tesscut` does not seem to do any caching.  We should look into supporting this.

Fortunately, `search_targetpixelfile` does have caching, so if the target has 2-minute cadence data available (which is the case for TIC149971754 in this example), then using `search_targetpixelfile` instead of `search_tesscut` will speed things up significantly!  Of course you will receive a different data product in this case (i.e. a 2-minute TPF instead of the 30-minute FFI cuts).

**Comment by mrtommyb** [comment]
It would be helpful if we can support caching of search_tesscut. I'm trying to download 28,000 FFI cutout. Caching results would be handy.

**Comment by barentsen** [comment]
Just recording here that `lightkurve.search_tesscut()` wraps `astroquery.mast.TesscutClass`, so we'll want to look into the caching mechanisms of astroquery.  Any takers?

**Comment by gully** [comment]
Are there any synergies with [eleanor](https://github.com/afeinstein20/eleanor) here?  What do they do?

**Comment by barentsen** [comment]
Although caching would be *really* valuable, we do not have the person-power required to add this feature to Lightkurve at this time, so I'm going to close this issue.

Fortunately a discussion has started to support caching as part of astroquery, here: https://github.com/astropy/astroquery/pull/1578

**Comment by barentsen** [comment]
Correction: the fabulous @nksaunders implemented TESSCut caching.  It has been merged into Lightkurve yesterday and will be part of v1.9!
