### ISSUE TITLE
KeplerTargetPixelFileFactory does not output a WCS to the new TPF

### ISSUE THREAD

**Issue by amcody** [KeplerGO/lightkurve#480]
The KeplerTargetPixelFileFactory and method from_fits_images needs to take the WCS solution of the input reference image, and send it to the output target pixel file. It is instead sending a null solution. It looks to me like the ext_info dictionary is only currently holding 1CRV5P and 2CRV5P, whereas it needs more keys to encapsulate the WCS. I will elaborate more on this later with some examples.

**Comment by barentsen** [comment]
Thanks for reporting this issue @amcody! :+1:

A good first step towards resolving this issue could be to open a PR with a unit test that fails.  Then, when we push the solution to the same PR, we can verify that the bug is resolved and ensure that it is never re-introduced.

(Not every bug can be reproduced into a simple unit test, but it is worth trying -- wanna have a go?)
