### ISSUE TITLE
.interact() tpf is blank

### ISSUE THREAD

**Issue by emilygilbert** [KeplerGO/lightkurve#501]
#### Problem description

When plotting sector 8 TESS data with 'interact()', pixel data does not plot accurately. Potentially due to the change in postage stamp size for sector 8?

<img width="771" alt="interact()_fail" src="https://user-images.githubusercontent.com/8570246/56530336-d133d900-6517-11e9-9b7d-40d3df0fd60b.png">

#### Example

```python
import lightkurve
tpf = lightkurve.search_targetpixelfile('L 98-59').download_all()
tpf[2].interact()
# earlier sectors (tpf[0] and tpf[1]) have no issues
```
#### Expected behavior
<img width="724" alt="interact()_success" src="https://user-images.githubusercontent.com/8570246/56531736-22dd6300-651a-11e9-99ca-28e3696fa920.png">

#### Environment:
- platform (e.g. Linux, OSX, Windows): OSX
- lightkurve version (e.g. 1.0b6): 1.0.0
- installation method (e.g. pip, conda, source): pip

**Comment by barentsen** [comment]
Thank you for reporting this issue @emilygilbert.  You are definitely encountering some unexpected behavior there!

/cc @gully can you have a look?

**Comment by gully** [comment]
Hi @emilygilbert,
Thank you for reporting the issue with helpful screenshots to help diagnose the phenomenon you are seeing.  The all-yellow pixels are a result of an imbalanced screen stretch normalization.
The default screen stretch for `interact()` is usually pretty sensible for most well-behaved data.  Your TPF-of-interest exhibits an extreme dynamic range, apparently due to an instrumental artifact in the middle third of the time window.  Luckily, the screen stretch can be controlled in the bottom right "Screen Stretch (log)" slider bar.  Does updating the screen stretch slider solve your problem?

While investigating your TPF, I noticed that something else seems to be affecting this target pixel file:  The mapping from cadence to the display window seems inaccurate.  Sometimes I observe all-gray pixels---which represent NaN data---even when the vertical red cadence indication bar points to a valid position in the lightcurve.

**Comment by gully** [comment]
Quick followup: 
The latter issue seems to be related to some unknown source of hysteresis between the mask pixel-selection assignment, screen stretch, and time series plot range.  If you notice some unusual behavior, I recommend a temporary workaround of adding-and-removing pixels in your mask.  You can use shift-click to toggle pixels on-and-off, though watch out for the inability to deselect the most-recently-selected pixel.

**Comment by emilygilbert** [comment]
Yes, stretching helps! Thanks, that's a good tip!
<img width="734" alt="Screen Shot 2019-04-24 at 12 29 15 PM" src="https://user-images.githubusercontent.com/8570246/56680376-c5b5ee80-668c-11e9-9d8f-19cc82a9afaf.png">

I tested this on ~50 sector 8 targets, and they all have the same issue. I know sector 8 had some spacecraft anomalies, so I guess that's not too surprising. I can send you an example notebook if that'll help!

**Comment by gully** [comment]
Good, glad that the screen stretch resolved the problem!  

I suspect all TESS Sector 8 targets will exhibit the same screen stretch default appearance.  What's happening behind the scenes, is that lightkurve computes the 1% and 95% percentile across all finite pixel values in the TargetPixelFile.

```python
vlo, lo, hi, vhi = np.nanpercentile(tpf.flux - pedestal, [0.2, 1, 95, 99.8]) # line 312 of interact.py
```
Sector 8 is apparently an exception, because 1% of the cadences have extremely low values, *and* these anomalously-low-values are not automatically masked with quality flags.

We could consider increasing the `lo` threshold default to, say, 5%.  That threshold might be too high for other, more typical TPFs.  We've found 1% and 95% to be decent threshold defaults for a wide range of Kepler and TESS data.  

If you want to over-ride the hardcoded 1% for yourself, you could [install the lightkurve developer version](http://docs.lightkurve.org/about/install.html#installing-the-development-version) alter line 312 of the file `interact.py`, and relaunch your jupyter-notebook.
