### ISSUE TITLE
No data found for some TOIs in Cycle1

### ISSUE THREAD

**Issue by jlillo** [KeplerGO/lightkurve#554]
#### Problem description
I am trying to retrieve TOI lightcurves extracted by the TESS pipeline with lightkurve, so the PDCSAP_flux. In more cases than expected I get the message "No data found for target [TIC_ID]". 

#### Example

```python
from lightkurve import search_lightcurvefile
lcfs = search_lightcurvefile(231663901).download_all(quality_bitmask='none')
```

#### Expected behavior
I would have expected this files to exist at least for all TOIs found by the TESS team.

#### Environment:
- platform: Mac OS sierra
- lightkurve version v1.1.0 running on Python 2.7:
- installation method (e.g. pip, conda, source): pip

**Comment by barentsen** [comment]
Thank you for reporting this issue @jlillo!
 
The problem is that 231663901 is also a K2 EPIC ID at a completely different position in the sky.  The solution is to search for `"TIC 231663901"` instead of `231663901`.

We definitely need to update lightkurve to provide the user with a warning in this situation!

**Comment by jlillo** [comment]
Oh! That explains that. Thanks a lot @barentsen!
