### ISSUE TITLE
TPFMaker doesn't return the right number of cadences.

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#58]
In PR #41 there is a problem with the number of time stamps not being returned. See below:

<img width="1166" alt="screen shot 2018-02-28 at 7 29 28 pm" src="https://user-images.githubusercontent.com/14965634/36825706-c76aff1e-1cbd-11e8-8199-3faf2987954e.png">

Not sure what's going on here, can't see why it would only return 4 of the time stamps requested.

**Comment by barentsen** [comment]
@gully investigated this today.  It turned out that the `KeplerTargetPixelFile` did contain the correct number of timestamps, however they were being masked out by the quality mask because most of the cadences in the Kepler cluster data have the "cosmic ray in optimal aperture" quality flag set.

Over in #41 we implemented two workarounds:
1. The "cosmic ray in optimal aperture" was moved from DEFAULT_BITMASK to HARD_BITMASK.
2. The `from_fits_images` method now accepts a `quality_bitmask` parameter.

(Caution: it is not clear yet that the move of the cosmic ray flag to HARD_BITMASK is a good idea.  Time will tell as we continue to use lightkurve.)
