### ISSUE TITLE
Data search via MAST no longer returns correct lightcurves.

### ISSUE THREAD

**Issue by ojhall94** [KeplerGO/lightkurve#584]
When searching a light curve file using an identifier (e.g. '16CygB', or a KIC number), the list of lighcurves returned are from a range of different targets, instead of the requested target.

```python
import lightkurve
data = lk.search_lightcurvefile('16CygB').download_all()
>>> data
LightCurveFileCollection of 26 objects:
	KIC 100002399 (1 KeplerLightCurveFiles) Quarters: 6
	KIC 100002401 (1 KeplerLightCurveFiles) Quarters: 6
	KIC 100002403 (1 KeplerLightCurveFiles) Quarters: 6
	KIC 100002741 (3 KeplerLightCurveFiles) Quarters: 7,11,15
	KIC 100002743 (1 KeplerLightCurveFiles) Quarters: 7
	KIC 100002745 (1 KeplerLightCurveFiles) Quarters: 7
	KIC 100003083 (3 KeplerLightCurveFiles) Quarters: 8,12,16
	KIC 100003085 (1 KeplerLightCurveFiles) Quarters: 8
	KIC 100003087 (1 KeplerLightCurveFiles) Quarters: 8
	KIC 100003502 (1 KeplerLightCurveFiles) Quarters: 9
	KIC 100003505 (1 KeplerLightCurveFiles) Quarters: 9
	KIC 100003508 (1 KeplerLightCurveFiles) Quarters: 9
	KIC 100003551 (2 KeplerLightCurveFiles) Quarters: 10,14
	KIC 100003554 (1 KeplerLightCurveFiles) Quarters: 10
	KIC 100003557 (1 KeplerLightCurveFiles) Quarters: 10
	KIC 100004031 (2 KeplerLightCurveFiles) Quarters: 13,17
	KIC 12069424 (4 KeplerLightCurveFiles) Quarters: 0,1,2,5
```
For reference, the correct KIC number for 16 Cyg B is: 12069449, which doesn't show up in the search at all.

I'm using lightkurve version 1.1.1.

Any ideas? @danhey has noticed this too and we think its a MAST issue, not lightkurve, but it's important to flag it here as it will break any automated algorithm.

**Comment by warrickball** [comment]
Curiously, KIC 12069424 is 16 Cyg A. Is this specific to 16 Cyg B? Has it worked before or is this the first time you've tried 16 Cyg B? I defer to someone more familiar with the data but I'm pretty sure 16 Cyg AB had special pixel masks to capture more of the bleeding columns. I just downloaded the short cadence FITS file for KIC 100002399 via FTP and the co-ordinates do point very close to 16 Cyg.

If you plot the power spectrum anyway, do you see the oscillations?

**Comment by barentsen** [comment]
It looks like searching for 16 Cyg B data is confusing because the target was observed under a range of different target mask identifiers (e.g. 100002741 in Q11 & Q15, 100004031 in Q13 & Q17).  This will be explained by the fact that the star is extremely bright (V~6).  Kepler's standard method of allocating masks was not designed for such bright objects, so I believe that custom masks were manually designed to observe this target (i.e. it is a very special case).  The person who designed the masks and will know the full details is steve.bryson@nasa.gov .

A side-effect of using custom masks is that they are observed under awkward target mask identifiers (1000xxxxx), rather than the standard KIC identifier.  Moreover, the target mask identifiers will change between Quarters for custom masks.

@ojhall94 Does that make sense?  Were you able to piece the data for 16 Cyg B together?  Note that the object was observed in short cadence, but `search_lightcurvefile` will only return long cadence by default.

**Comment by barentsen** [comment]
A consequence of the different target ID's is that stitch refuses to work:
![Screenshot from 2019-09-06 08-54-41](https://user-images.githubusercontent.com/817669/64442069-059dd100-d084-11e9-84b1-3275efb900c8.png)

...but the following hack works around the restriction:

![Screenshot from 2019-09-06 08-54-25](https://user-images.githubusercontent.com/817669/64442100-12222980-d084-11e9-8849-f163188f857c.png)

**Comment by barentsen** [comment]
I am going to close this issue because I believe the problem has been clarified/resolved.

Please do re-open the issue or leave a comment if anyone needs further help!
