### ISSUE TITLE
Incorrect TIC ID returned using get_lightcurvefile

### ISSUE THREAD

**Issue by zclaytor** [KeplerGO/lightkurve#601]
#### Problem description

When using lightkurve to retrieve TESS data, search_lightcurvefile (and search_targetpixelfile) return the wrong TIC ID, even when 'TIC' is included in the target name or when 'TESS' is specified as the mission.

#### Example

```python
import lightkurve as lk
lk.search_lightcurvefile('TIC 734501845')
```
I get the following output:
```
SearchResult containing 3 data products.

target_name                     productFilename                     description  distance
----------- ------------------------------------------------------- ------------ --------
  350741703 tess2018263035959-s0003-0000000350741703-0123-s_lc.fits Light curves      0.0
  350741703 tess2018292075959-s0004-0000000350741703-0124-s_lc.fits Light curves      0.0
  350741703 tess2018319095959-s0005-0000000350741703-0125-s_lc.fits Light curves      0.0
```

#### Expected behavior

I expected to get light curve files for TIC 734501845, but I received a list of files for TIC 350741703.

#### Environment

-  platform: Ubuntu 19.04
-  lightkurve version: 1.2.0
-  installation method: conda

**Comment by barentsen** [comment]
@zclaytor Thank you for getting in touch!

Behind the scenes, MAST resolves the object identifier (TIC 734501845) into sky coordinates, and then performs the data search using those sky coordinates.  It looks like you are receiving data for TIC 350741703 because it is associated with the ~same position on the sky as TIC 734501845:

![Screenshot from 2019-10-02 18-58-48](https://user-images.githubusercontent.com/817669/66093925-f0af4300-e546-11e9-9264-cf387fc5689a.png)

So I think the real question is: *"why was an object observed under name TIC 350741703 when you expected it to be called TIC 734501845"*.  I cannot answer that question, but one of the following people may be able to: @mrtommyb  @christopherburke @scfleming @mustaric

**Comment by mustaric** [comment]
It looks like those two stars are 0.4 arc seconds apart. You can see this if you do a cone search on the TIC. Because it's footprint at MAST overlaps the observed star, you get it back with the lightkurve query. TIC 350741703 was chosen as part of Dressing's program, G011180.

**Comment by scfleming** [comment]
![ticgaiaids](https://user-images.githubusercontent.com/1542158/66131194-fa758c80-e5c0-11e9-918c-e7c5f27cf434.png)
 To expand a bit further, these two TIC IDs in question correspond to two different Gaia DR2 IDs (see attached screenshot).  It was the other TIC that got observed (technically).  I don't know if this system is a close binary, or the two Gaia IDs really should be the same star, but there is no TESS light curve for 734501845 under that name, you'd have to use the light curve for TIC 350741703.

**Comment by scfleming** [comment]
This brings up an interesting decision for the lightkurve development: one could avoid this by using Observations.query_criteria() and matching directly on mission name and target names if given a KIC/EPIC/TIC ID, instead of doing a cone search.  That would always provide the user with light curves or target pixel files for exactly that star ID only.  But, if a user isn't aware of a case where the mission's data might be under a different ID than they expect, for whatever reason, then they would not discover that by doing a cone search.  Perhaps the default of doing a cone search, but with a "--exact" option that would instead match directly on the IDs and not do a cone search could cover both scenarios, but may add more complexity than you want.

**Comment by gully** [comment]
I'm in favor of the `exact=True` option.  There's another edge-case scenario that comes up occasionally, in which both sources share the same coordinates to within arbitrary precision, and were both assigned TPFs.  Basically, two sources in the KIC are unresolved binary components that were not filtered out before getting assigned postage stamps.  For example:

`lk.search_targetpixelfile('KIC 1162345', mission='Kepler', radius=0.00000001)`

yields distinct TPFs for both `KIC 1162339` and `KIC 1162345`.

I've had two workarounds here: one is to use `.interact_sky()` to compare the two TPFs and I quickly realize that they are TPFs of the same fields but with different aperture choices, likely due to the different magnitudes of the KIC inputs.  Gaia doesn't necessarily resolve the components-- after all they were unresolved in existing imaging when the KIC was made.  One problem is that interact_sky() currently only lists Gaia IDs.  It'd be awesome to have interact_sky also list KIC and TIC IDs if available.  Then you'd see that two KIC IDs match to the same Gaia source, for example.  

My other workaround to sanitize the output has been:

```
sr = lk.search_targetpixelfile('KIC 1162345', mission='Kepler', radius=0.00000001)
match_indices = [i for i, v in enumerate(sr.target_name) if '1162345' in v]
sr[match_indices]
```

So I'd be in favor of adding a `exact=True` kwarg that essentially does the latter work around---or better yet `Observations.query_criteria()`--- behind the scenes.

**Comment by gully** [comment]
As always, the name `exact` could be subject to discussion, since exact could have ambiguous connotations (exact in what sense?), the main idea is to filter out duplicates, or match on duplicates, depending on the use case.

**Comment by barentsen** [comment]
I am inclined to follow the philosophy that "every search is a cone search" (consistent with the MAST portal), and teach users how to mask the search result if further filtering is required.

Similar to Gully's example, this would've worked if a target had been observed under the identifier TIC 734501845:

```python
import lightkurve as lk
search = lk.search_lightcurvefile('TIC 734501845')
search[search.target_name == '734501845'].download_all()
```

**Comment by barentsen** [comment]
I am going to close this issue because I don't think there is an actual bug here -- but please do comment or re-open if anyone thinks we should discuss this in more detail!

**Comment by zclaytor** [comment]
This was really enlightening discussion. Thanks!
