### ISSUE TITLE
Lightcurve not found for ε Coronae Australis when using `eps cra` but found with HR designation `HR 7152`

### ISSUE THREAD

**Issue by warrickball** [KeplerGO/lightkurve#615]
## Problem description

`lightkurve` fails to return a lightcurve for the star [ε Coronae Australis](http://simbad.u-strasbg.fr/simbad/sim-basic?Ident=eps+cra) when I use its abbreviated name (i.e. `eps cra`) but succeeds when using another designation (`HR 7152`). `lightkurve` also succeeds when I use a similar name for a star in another constellation (e.g. `eps crt` for [ε Crateris](http://simbad.u-strasbg.fr/simbad/sim-basic?Ident=eps+crt)).

As a rudimentary demonstration, the following script
```python
import lightkurve as lk

lcs = lk.search_lightcurvefile('eps crt', mission='TESS', cadence='short').download_all()
print(len(lcs)) # 1
lcs = lk.search_lightcurvefile('hr 7152', mission='TESS', cadence='short').download_all()
print(len(lcs)) # 1
lcs = lk.search_lightcurvefile('eps cra', mission='TESS', cadence='short').download_all()
print(len(lcs))
```
produces the output
```
1
1
/home/wball/.local/lib/python3.7/site-packages/lightkurve/search.py:229: LightkurveWarning: Cannot download from an empty search result.
  LightkurveWarning)
Traceback (most recent call last):
  File "issue.py", line 10, in <module>
    print(len(lcs))
TypeError: object of type 'NoneType' has no len()
```

This is with `lightkurve` version 1.3.0 and Python 3.7.4 installed via `pip3` on Fedora 30.
```
$ python3 -V
Python 3.7.4
$ pip3 show lightkurve
Name: lightkurve
Version: 1.3.0
Summary: A friendly package for Kepler & TESS time series analysis in Python.
Home-page: https://docs.lightkurve.org
Author: KeplerGO
Author-email: keplergo@mail.arc.nasa.gov
License: MIT
Location: /home/wball/.local/lib/python3.7/site-packages
Requires: astropy, scipy, oktopus, uncertainties, requests, numpy, astroquery, pandas, tqdm, bs4, matplotlib
$ cat /etc/fedora-release 
Fedora release 30 (Thirty)
$ uname -r
5.2.17-200.fc30.x86_64
```

**Comment by barentsen** [comment]
@warrickball thanks for taking the time to report this!

Short answer: MAST's name resolver does not resolve `eps cra` and `hr 7152` to the same coordinates. You can work around your problem by adding `radius=10` to your search:

![Screenshot from 2019-10-23 08-09-49](https://user-images.githubusercontent.com/817669/67407548-83526900-f56c-11e9-9bc3-d74059f73721.png)

Longer answer: MAST surprisingly resolves `eps cra` and `hr 7152` to different coordinates separated by 8 arcseconds:

![Screenshot from 2019-10-23 08-04-50](https://user-images.githubusercontent.com/817669/67407106-df68bd80-f56b-11e9-8844-cb3bc8744f31.png)

In contrast, the CDS name resolver (accessed via astropy) returns identical coordinates:

![Screenshot from 2019-10-23 08-09-19](https://user-images.githubusercontent.com/817669/67407621-a67d1880-f56c-11e9-94e7-fed4b5bc2569.png)

I'm not sure what the reason is behind this mismatch, or how frequently this occurs, but I'll tag some of the wonderful people at MAST in case they're interested in looking into the issue: @mustaric @scfleming @ceb8

**Comment by scfleming** [comment]
The name resolver at MAST first tries NED and Simbad (I think in that order), and in this case I think since NED resolves both of these (to different coordinates for whatever reason), that is the difference.  I might put in a ticket to allow an optional argument to our name resolver to try only one of those services for cases like this.

**Comment by barentsen** [comment]
@scfleming Rather than making it an extra option, would it be sensible for MAST to query Simbad first and then NED?  I'm saying this because I'm *guessing* that Simbad does a better job at published objects, and NED complements it by adding lots of lower-importance, unpublished objects, so it makes sense to query in that order?  (But I may be very wrong.)

**Comment by scfleming** [comment]
You are thinking like a Kepler scientist :)  I am not certain that is the case for extragalactic queries, which is also a bulk of MAST query usage.  Unfortunately I don't think any default order will be optimal for all queries.

**Comment by barentsen** [comment]
My bias shows! =)

Of course the easiest solution for everyone is if NED returned accurate coordinates for bright stars.  I haven't seen this problem before so it may be a freak issue, but it may nonetheless be worth reporting to NED? @scfleming are you planning on doing so, or shall I?

**Comment by scfleming** [comment]
I wasn't planning on doing that per se, so feel free to get in touch with the NED folks.

**Comment by barentsen** [comment]
For what it's worth: when I query these objects by name on the NED website, I find that `eps cra` resolves to coordinates taken from the ROSAT all-sky survey bright source catalogue (whereas `hr 7152` resolves to 2MASS).

So, an X-ray catalog is being used to determine the position of a naked-eye star  🤔  This may really just be a freak case, but we'll want to keep an eye on it.

**Comment by barentsen** [comment]
Update: NED told me they will link together `eps cra` and `hr 7152`as one object in their database.  🎉
