### ISSUE TITLE
Convenience methods for accessing a lightcurve by sector

### ISSUE THREAD

**Issue by orionlee** [KeplerGO/lightkurve#621]
#### Problem description
It'd be more productive if the package provides a way access a `LightCurveFile` among in a `LightCurveFileCollection` by sector. It could make some codes more readable.

#### Example

```python
import lightkurve as lk

# get the lightcurves for a given target
lcf_coll = lk.search.search_lightcurvefile(target='TIC232612416', mission='TESS').download_all()

# proposed new method
lc14 = lcf_coll.get_by_sector(14)

lc14.PDCSAP_FLUX.plot()
```

The new method, tentatively `get_by_sector(sector_num)`, returns the `LightCurveFile` of a given sector. 

The behavior when there are multiple `LightCurveFile` instances with the same sector: throw exception, or maybe return the first one with warnings.

#### Environment

-  lightkurve version (e.g. 1.0b6): 1.3.0

**Comment by barentsen** [comment]
Thanks @orionlee!  This is an interesting idea.  :+1:  It makes sense to me that users will want to select items from a collection by sector or quarter.

Currently, one can obtain the files for a specific sector by passing the `sector` argument to the search function, example:
```python
lcf_coll = lk.search.search_lightcurvefile(target='TIC232612416', mission='TESS', sector=14).download_all()
```

Of course this is slow right now because we don't have caching working on the search operation yet.

Rather than adding a method, I wonder if the best way to support this is to add a `lcf_coll.sector` property (alongside `lcf_coll.campaign` and `lcf_coll.quarter` properties).  That way, one could select by sector using:
```python
lcf_coll[lcf_coll.sector == 14]
```

But this would also enable more powerful expressions, e.g.:
```python
lcf_coll[(lcf_coll.sector > 10) & (lcf_coll.sector < 15)]
```

What do you think?

**Comment by orionlee** [comment]
The suggestion of using properties ```lcf_coll[lcf_coll.sector == 14]``` is better. It's a pattern that lightkurve users should be familiar with.
