### ISSUE TITLE
Plot graphs using relative time

### ISSUE THREAD

**Issue by orionlee** [KeplerGO/lightkurve#622]
#### Problem description

Sometimes it is preferable to plot lightcurves using relative time (from the start of observation).

It'd be great if the supplied plotting methods (`plot()`, `scatter()`, etc.) allow such options.

#### Example
```python
# get the lightcurves for a given target
lcf_coll = lk.search.search_lightcurvefile(target='TIC232612416', mission='TESS').download_all()

lc = lcf_coll[0]

# new parameter for relative time
lc14.PDCSAP_FLUX.plot(use_relative_time=True)

```

The output would be something like this:

![image](https://user-images.githubusercontent.com/250644/68058373-1a7a9780-fcb6-11e9-8cc3-0d65a4f90743.png)

#### Environment

-  lightkurve version (e.g. 1.0b6): 1.3.0

**Comment by barentsen** [comment]
Thanks for the suggestion @orionlee!  :+1:

I guess what you describe is possible right now by doing this:
```python
lc.time -= np.min(lc.time)
lc.plot()
```

Some questions that pop up in my brain:
* Is this a sufficiently common operation to warrant a dedicated keyword?
* Is it OK to encourage users to plot light curves this way? (information is removed)
* Can you list a few specific examples where this would clearly be handy?

(PS: We *always* try to come up with arguments against adding a new feature, because new features require extra testing+maintenance, require users to read more docs, and are difficult to remove once added.  Of course we do want to add features if they are useful, so please do argue in favor if you think this keyword would make Lightkurve better!)

**Comment by orionlee** [comment]
I started using `lightkurve` in conjunction with Planet Hunters TESS, so the use cases might be slightly different from those of the professionals.
1. Planet Hunters TESS displays lightcurve in relative time ([example](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/talk/subjects/32635244)). So it'd be more convenient to plot graphs in the same way for comparison: less mental conversion.
2. Sometimes I plot the lightcurves of same target from multiple sectors, as multiple subplots stacked vertically. I find using relative time is more convenient in such case.

---
Regarding information loss: a mitigation could be displaying the start time as part of x-axis title.

---
If it's decided the use cases warrant some support from `lightkurve`, an alternative to adding new parameters to different charting functions would be to add a function to `LightCurve.use_relative_time(enabled)` .  However, I fear it might have some unintended side effects, e.g., should setting to relative impact non-charting functions?

**Comment by barentsen** [comment]
I'm inclined to close this issue for now because we are running out of person-power to support new features, and I believe we support plots in relative time via e.g.:
```python
lc.time -= np.min(lc.time)
lc.plot()
```

Please do re-open this issue if anyone feels strongly that a change in Lightkurve is needed to accommodate different X axes labels. Thanks everyone! :+1:
