### ISSUE TITLE
Can I change the axis range of the graph?

### ISSUE THREAD

**Issue by ansainbdg** [KeplerGO/lightkurve#673]
Can I change the axis range of the graph?

ex.When I created lightcurve of a star using Lightcurve.plot(or errorbar,scatter), the default y-axis range is from 180,000 to 190,000. How do I change y-axis range?

-  platform (Windows):
-  lightkurve version (1.6.0):
-  installation method (pip):

**Comment by christinahedges** [comment]
Hi @ansainbdg 

Thanks for opening an issue! Yes you can change the y-axis in `lightkurve` plots. `lightkurve` returns a `matplotlib.axes` object. If you're familiar with `matplotlib`, you can use all the same methods on this object. (You can see some of the methods in the `matplotlib` docs [here](https://matplotlib.org/api/axes_api.html).) I'm adding a quick demo below to show you how you would change the y-axis:

![image](https://user-images.githubusercontent.com/14965634/73312020-a1b7a880-41dc-11ea-947b-f18b711c51aa.png)

If you're using a jupyter notebook, remember that you need to do this in the same cell where you made the plot, otherwise it won't update. 

If you have any more problems or questions please feel free to reach out and open another issue!
