### ISSUE TITLE
'TessTargetPixelFile' object has no attribute 'prf_lightcurve'

### ISSUE THREAD

**Issue by xyz3919** [KeplerGO/lightkurve#677]
I was trying to produce light curves from PRF photometry with TESS tpf. However, I encountered the error below saying the 'TessTargetPixelFile' object has no attribute 'prf_lightcurve'. It seems the TESS tpf haven't supported the PRF photometry?

```
>>> tpf
TessTargetPixelFile(TICID: 261136679)
>>> tpf.to_lightcurve(method='prf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ycchen/.local/lib/python3.6/site-packages/lightkurve/targetpixelfile.py", line 374, in to_lightcurve
    return self.prf_lightcurve(**kwargs)
AttributeError: 'TessTargetPixelFile' object has no attribute 'prf_lightcurve'
```

**Comment by barentsen** [comment]
Hi @xyz3919!

Unfortunately, yes, we have not tested or integrated the PRF photometry methods for use with TESS.  In fact we may remove the PRF photometry methods from Lightkurve altogether because they have not been validated/tested extensively.

Nevertheless, if you'd like to play around with it more, I would recommend having a look at the implementation of the `KeplerTargetPixelFile.extract_prf_photometry()` method which will show you how you may be able to do PRF photometry on TESS!

**Comment by xyz3919** [comment]
Thanks for the reply! 
I have another question about changing the properties of TPF file.
I would like to change the flux in tpf like `tpf.flux=tpf.flux*2`.
But it always shows `AttributeError: can't set attribute`. 
I was able to modify the lightcurve file. Are the attribute in tpf file meant to be unchanged?

**Comment by barentsen** [comment]
Yes, unfortunately most attributes of a `TargetPixelFile` cannot be changed because the object is still a wrapper around a FITS file.  We hope to change this in the future.

In meanwhile, a workaround hack to e.g. multiply the flux by 2 is to do this:
```python
tpf.hdu[1].data['FLUX'] = tpf.hdu[1].data['FLUX'] * 2
```
After executing the line above, you should find that `tpf.flux` has been multiplied by 2!

**Comment by xyz3919** [comment]
The workaround works perfectly! I really appreciate it! Thanks.

**Comment by barentsen** [comment]
My pleasure! :+1:
