### ISSUE TITLE
Should we standardize lightkurve warnings?

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#691]
Inside lightkurve we have two different ways to warn users about problems:

`log.warning('Cannot find Campaign or Quarter number.')`
`warnings.warn('`transit_midpoint` is deprecated, please use `t0` instead.',
                          LightkurveWarning)`

It's not clear to me why we have two different ways to warn users, and it feels like we should use the second way everywhere. Should we standardize this so that people contributing code know how to raise warnings and errors? @barentsen can you tell us the right™️ answer?

**Comment by barentsen** [comment]
## Geert's Right Answer:tm:

We should (almost) never use `log.warning` or `log.error`.  Here's my take:

1. Whenever possible, we should design APIs that prevent errors.  For example, when an unobserved target is requested, `search` functions should return an empty `SearchResult` rather than an ugly error.
2. For emitting messages that help diagnose what Lightkurve is doing, we should use `log.debug()` and `log.info()`.  This may e.g. help a user understand why the `SearchResult` was empty.
3. When a user makes a benign mistake that should trigger them to fix their code, `warnings.warn` should be used to notify them.  The classic example is a `DeprecationWarning`.
4. When a fatal mistake is encountered, an `Exception` should be raised.

## Background

The Python docs (https://docs.python.org/3/howto/logging.html#when-to-use-logging) recommend the following:
* use warnings.warn() in library code if the issue is avoidable and the client application should be modified to eliminate the warning
* use logging.warning() if there is nothing the client application can do about the situation, but the event should still be noted.

...however I feel that we should design the API to avoid the latter as much as possible.  A rare exception is when a feature is designed to be called exclusively by hand (e.g. `tpf.interact()`), in which case using `log.error("you need to set the notebook url")` leads to a more user-friendly experience than raising an exception.

## Footnote 

The occurence of `log.warning` you refer to shouldn't exist:

https://github.com/KeplerGO/lightkurve/blob/b93605f0b753e725d546527fa7b1657c2fd7bc7a/lightkurve/lightcurve.py#L1899

...when a light curve does not have a quarter or campaign keyword, the API should just gracefully set it to `None` and not be noisy about it.

Does that make sense?
