### ISSUE TITLE
Check whether aperture_mask is a boolean

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/lightkurve#694]
#### Problem description
If an integer array is passed to aperture mask rather than a boolean it gives a cryptic error message.

#### Example

For example the following fails
```python
import lightkurve as lk
tpf = lk.search_targetpixelfile('YZ CMi').download()
aperture = np.zeros(tpf[0].shape[1:], )
aperture[-7:-3,4:8] = True
lc = tpf.to_lightcurve(aperture_mask=aperture);
lc.plot()
```
But this is successful
```python
import lightkurve as lk
tpf = lk.search_targetpixelfile('YZ CMi').download()
aperture = np.zeros(tpf[0].shape[1:], dtype=bool)
aperture[-7:-3,4:8] = True
lc = tpf.to_lightcurve(aperture_mask=aperture);
lc.plot()
```

#### Expected behavior

If a non-boolean type is passed print an error message that tells the user to pass a boolean

**Comment by barentsen** [comment]
Thanks for opening this issue @mrtommyb. :+1:

Over in https://github.com/KeplerGO/lightkurve/commit/2495462a72e0a67467288a7e171f1181230ac53a I changed the behavior of `tpf._parse_aperture_mask()` to automatically convert integer/float masks to boolean type, so that the example you posted Just Works (tm) without bothering the user with errors:

![Screenshot from 2020-08-28 16-10-29](https://user-images.githubusercontent.com/817669/91621769-291ef300-e949-11ea-9373-270317ba53b2.png)

I also added a unit test for this.  Closing the issue!
