### ISSUE TITLE
plot_river function

### ISSUE THREAD

**Issue by rebekah9969** [KeplerGO/lightkurve#719]
Where is the plot_river defined. I note it is in the lightkurve code, but is it documented anywhere?
The tutorial using this function is wonderful.

**Comment by barentsen** [comment]
`plot_river` is a method of the `LightCurve` class, and so it should show up in the online API docs on the page of that class.

I see that the `plot_river` has somehow not made its way into the online docs.  This will be due to a caching issue in the docs generation.  Thanks for reporting!  Will fix!

**Comment by barentsen** [comment]
This bug has been fixed; `plot_river` now shows up in the API docs:

https://docs.lightkurve.org/api/lightkurve.lightcurve.LightCurve.html#lightkurve.lightcurve.LightCurve.plot_river

Thanks @rebekah9969! :+1:
