### ISSUE TITLE
Windows 10 lightkurve installation problem

### ISSUE THREAD

**Issue by christandoi** [KeplerGO/lightkurve#721]
Ran into an issue with `pip install lightkurve` on Windows 10, told to install Microsoft Visual C++ 14.0 even though I had that installed already.

Fixed the issue by following the instructions on this link: 

https://www.scivision.dev/python-windows-visual-c-14-required/

had to download build tools for Visual Studio and then install the Windows 10 SDK and C++ x64/x86 build tools to get it running.

#### Environment
-  platform (e.g. Linux, OSX, Windows): Windows 10 version 1903 OS build 18362.720
-  lightkurve version (e.g. 1.0b6): 1.9.1
-  installation method (e.g. pip, conda, source): pip

**Comment by barentsen** [comment]
@christandoi Thank you so much for reporting this issue! :pray: 

Lightkurve itself does not require a C++ compiler, so this error message must have been triggered by one of the packages Lightkurve depends on.

By any chances, do you still have a log/record of the installation process?  I would love to understand which package required the C++ compiler.

An alternative workaround for anyone encountering this issue is to install Lightkurve via the anaconda Python distirbution ([instructions here](https://docs.lightkurve.org/about/install.html#using-conda)), which will not require a compiler.

**Comment by barentsen** [comment]
I'm going to close this issue due to inactivity.  I encourage anyone struggling with this problem to re-open this issue with more information!
