### ISSUE TITLE
Add from_fits_images method to TESSTargetPixelFile class

### ISSUE THREAD

**Issue by burke86** [KeplerGO/lightkurve#767]
I have a particular use-case which involves creating my own TESSTargetPixelFile objects from a list of FFIs (after performing some image processing on the FFIs).

My current workaround is to use the `KeplerTargetPixelFileFactory`, then hack the HDU keys to "trick" lightkurve into recognizing it as a TESS TPF. Something like:
```
factory = KeplerTargetPixelFileFactory(n_cadences, n_rows, n_cols, target_id)
for i in range(n_cadences):
    factory.add_cadence(frameno=i, flux[i], flux_err[i], header, flux_bkg[i], flux_bkg_err[i])
# Hack to create Kepler TPF that looks like a TESS TPF
ext_info = {}
ext_info.update(self.wcs_sec0.to_header(relax=False))
ext_info['telescop'] = 'tess'
ext_info['mission'] = 'tess'

#...etc...#

tess_tpf = factory.get_tpf(ext_info=ext_info)
```

This is probably not ideal or recommended, so it would be great for a `from_fits_images` method to be added for TESS TPFs.

**Comment by barentsen** [comment]
@burke86 Thank you for opening this issue! :+1:

You are absolutely right!  It's a bit silly that Lightkurve can make target pixel files for Kepler but not TESS.  This is merely because the feature was developed before TESS started operating.

The code snippet you posted looks like an excellent workaround.  It is what I would do!

Lightkurve should have a generic `TargetPixelFileFactory` that can work for any mission, not just Kepler.  I won't have time to work on this in the near future myself, but I can help someone else develop it.  @burke86 Would you be interested in having a go?

**Comment by burke86** [comment]
Hi @barentsen, yes I can give it a shot over the next few days and put in a pull request! I'll let you know if I have any questions.

**Comment by barentsen** [comment]
@burke86 That sounds awesome! :+1:

Without thinking about it too much, I suspect the required changes include:
* rename `KeplerTargetPixelFileFactory` into a generic `TargetPixelFileFactory`;
* modify `TargetPixelFileFactory.get_tpf()` to return a generic `TargetPixelFile` object;
* move `from_fits_images` from `KeplerTargetPixelFile` to `TargetPixelFile`.

But maybe you have better ideas!

Feel free to mess around and open a PR as soon as you want feedback, whether it works or not! :+1:

**Comment by burke86** [comment]
Thanks @barentsen! I have created an initial pull request here, https://github.com/KeplerGO/lightkurve/pull/768. Thanks for your help.

**Comment by burke86** [comment]
Thanks @barentsen, this was just merged so I will close this issue. No worries about the delay!
