### ISSUE TITLE
The use of .flux with different lightkurve objects

### ISSUE THREAD

**Issue by rebekah9969** [KeplerGO/lightkurve#781]
For a first time user the use of the .flux variable can be very confusing. 

For instance,
tpf_file.flux = is the FLUX column in the TPF file, which is a flat-fielded/bias-subtracted version of the raw electron counts
where as 
tpf_file.hdu[1].data['FLUX'] = does not have this flat-fielded/bias-subtraction - it is a rawer(?) version of the flux.

In addition for lightcurve objects made  via tpf.to_lightcurve
lc.flux = the SAP flux

However if you have a lightcurve file
lcf.flux = the PDCSAP which has the de-trending etc
and
lcf.sap_flux = the SAP flux you would get if you did lc.flux 

None of these are constant and make using .flux very complicated. There is no clear documentation of this and the current tutorials themselves are confusing on these points. 

A new naming convention might help e.g., flux_raw, flux1  = tpf_file.hdu[1].data['FLUX'], flux2 = tpf_file.flux, flux3 = lcf.sap_flux or lc.flux, flux4 = lcf.flux  - where the increase in number represents a level of processing.

The use of .flux for the "best flux" of  certain output is very subjective.

Better documentation would also aid this issue as well.

**Comment by barentsen** [comment]
Thanks @rebekah9969.  It is absolutely true that it is not always transparent what `flux` provides.  It is definitely worthwhile to reflect on how we can do better!

The current situation is as follows:
* `TargetPixelFile.flux` is equal to the quality-masked values held in `hdu[1].data['FLUX']` of a pixel file.  This is a 3D-array in (column, row, time) space from which cadences have been removed that violated the `quality_bitmask` parameter that is accepted when opening the file.  The philosophy is that `tpf.flux` provides the values you want to perform operations on (e.g. extracting a light curve).
* `LightCurve.flux` holds the flux values which all the light curve functions will operate on (e.g. plotting, binning, folding, etc.)  This is a 1D-array. When downloading an official light curve from MAST via `search_lightcurve(...).download()`, the `flux` column is automatically populated with PDCSAP_FLUX by default, but this is customizable.  This behavior will be different for e.g. HLSP light curve products held at MAST, because different products and pipelines use different column names, and a `LightCurve` object attempts to be a generic object to store any light curve.  The philosophy here too is that `lc.flux` provides the values you want to perform operations on, and that a decision on the choice of flux has been made before creating the object.

I wonder if we can address the confusion by making the meaning of the `flux` column visible and accessible.  Here is a screenshot of a simple hack, which demonstrates what it would look like if we clarified the meaning of the `flux` column as part of the screen representation of a LightCurve object:

![flux-explain](https://user-images.githubusercontent.com/817669/88217437-65a55380-cc13-11ea-8bfc-a8c9274d6092.png)

Would that help?  I'm happy to hear any and all recommendations for solutions!

**Comment by barentsen** [comment]
Additional idea: we could investigate having `tpf.flux` return a "masked array" object instead of a traditional array, which would make it explicit that some cadences have been masked.

**Comment by astrobel** [comment]
I've been thinking a lot about this, and I feel like there are no easy answers, so the best I can do is weigh in with how I use it so we can get a range of perspectives. I tend to do my own corrections on light curves, and I had also originally assumed that `lc.flux` would return SAP flux (as opposed to PDCSAP), since that is what's returned when you produce a light curve from `.to_lightcurve()`, and it's closer to the the "raw" (better word pending!) product.

I do way more work with TPFs than with light curves, and I found the transition from working directly with FITS files to interfacing with Lightkurve to be very intuitive. Would making `tpf.flux` a masked array cause much code to break? It seems fine as it is to me, but I'd be curious about the practicalities of the masked array option.

**Comment by barentsen** [comment]
I'm closing the issue for now because it has been inactive for several months.  I absolutely agree that we should continue to make sure that the meaning of the `flux` attribute is as clear as possible, e.g. via improved documentation and other methods.

I encourage anyone to re-open this issue with new insights or suggestions.
