### ISSUE TITLE
`sap_quality` and `quality` are unnecessary duplicates

### ISSUE THREAD

**Issue by ojhall94** [KeplerGO/lightkurve#787]
When downloading a Kepler light curve, the resulting `KeplerLightCurve` object will have both a `quality` and `sap_quality` column, which are identical.

I propose we only use one or the other. On the one hand, `sap_quality` provides a direct link to its description in the Kepler Archive Manual, but on the other, `quality` is more easily understood.

**Comment by barentsen** [comment]
This is a good and important question I'd love feedback on.  Please bear with me as I explain the origin of this:

### Why do KeplerLightCurve objects have `quality`, `centroid_col`, `centroid_row` columns?

This is a legacy of Lightkurve v1.x, where LightCurve objects had `quality`, `centroid_col`, `centroid_row`, `cadenceno`, etc hard-coded as class attributes (i.e. "columns").

In Lightkurve v2.x these columns are no longer hard-coded.  This is because `LightCurve` object became a sub-class of Astropy `TimeSeries` (which extends `Table`), so a light curve object now supports storing any user-defined columns.  The only exception are the `time`, `flux`, and `flux_err` columns, which the LightCurve API enforces to be populated.  i.e. the constructor of the `LightCurve` class will raise an error if these are not available, just like the constructor of the `TimeSeries` class raises an error if `time` is not set.

To maintain backwards-compatibility, the `KeplerLightCurve.read()` method in Lightkurve v2.x not only returns a `LightCurve` object with the columns present in the Kepler light curve FITS file, it also populates extra columns as follows:
* `flux` is populated with `sap_flux` or `pdcsap_flux` (this is configurable);
* `flux_err` is populated with `sap_flux_err` or `pdcsap_flux_err`;
* `centroid_col` is populated with `mom_centr1`;
* `centroid_row` is populated with `mom_centr2`;
* `quality` is populated with `sap_quality`.

The reason for populating `centroid_col`, `centroid_row`, and `quality` is to reduce breaking code, because existing users may expect them to be present just as they were in Lightkurve v1.x.

### What is the right behavior?

Going forward, we have the choice to:
* Option A: We could deprecate and remove `centroid_col`, `centroid_row`, and `quality` in favor of whatever these columns are known as in the FITS file.  This means these columns will have different names in light curves from different missions and community pipelines.
* Option B: We could always attempt to populate these columns so that users can reasonably expect them to be present, regardless of which pipeline produced the light curve and regardless of what name they used.

I would love to hear your opinions on this!

/polls "Option A: Only use column names present in FITS files" "Option B: Populate extra columns to provide uniform names"

**Comment by ojhall94** [comment]
Thanks for explaining @barentsen! This info is enough for me to explain in my tutorials. I personally think there is a use case for having these general columns that are duplicates of other information, so long as these are super well documented. Interested to see what others think!

**Comment by barentsen** [comment]
I'm going to close this issue for now, but I'm happy for anyone with extra thoughts/comments/suggestions to re-open and continue the discussion below!
