### ISSUE TITLE
Warning when running Regression Corrector Object

### ISSUE THREAD

**Issue by rebekah9969** [KeplerGO/lightkurve#792]
```
tpf_2min = lk.search_targetpixelfile(target, mission='TESS', sector=15).download()

aper = tpf_2min.pipeline_mask
sap_lc = tpf_2min.to_lightcurve()


dm = lk.DesignMatrix(tpf_2min.flux[:, ~aper], name='pixels').pca(5).append_constant()


reg = lk.RegressionCorrector(sap_lc)
corrected_lc = reg.correct(dm)
ax = sap_lc.errorbar(label='Raw light curve')
corrected_lc.errorbar(ax=ax, label='Corrected light curve');
```

Produces the warning  

LightkurveWarning: The design matrix has low rank (4) compared to the number of columns (114), which suggests that the matrix contains duplicate or correlated columns. This may prevent the regression from succeeding. Consider reducing the dimensionality by calling the `pca()` method.
  LightkurveWarning)

Any insight into this warning would be helpful.

**Comment by rebekah9969** [comment]
Apologies 

target = 'KIC 8462852'

**Comment by barentsen** [comment]
Thanks @rebekah9969!
 
It looks like the low matrix rank warning is issued by this statement:
```python
DesignMatrix(tpf_2min.flux[:, ~aper], name='pixels')
```

The warnings seems unnecessary here because the user is already addressing the low-rank situation with the call to `pca(5)`.

I wonder if we want to change the code such that only `RegressionCorrector.correct()` emits a warning about a low rank, i.e. we should only emit a low-rank warning if the matrix is actually used to perform regression.  Thoughts @nksaunders @christinahedges?  Any volunteers to fix this?
