### ISSUE TITLE
.interact() help

### ISSUE THREAD

**Issue by eugeneb5** [KeplerGO/lightkurve#794]
#### Problem description

I'm new to the platform (both coding and Jupyterlab, lightkurve, etc - so that may be part of the problem)...
In trying to use the .interact() action, just an error message of '3 cadences will be ignored' pops up - it simply states the flagged tpfs will be ignored but doesn't pop up with the interactive graph and pixel images with sliders, etc.

i've literally taken the code from:
https://docs.lightkurve.org/tutorials/04-interact-with-lightcurves-and-tpf.html 
and just applied it (only changing the to the data I want).

#### Environment
I am using Windows with v. 1.0b25 of lightkurve installed via conda.

I apologise for lack of any proper jargon and appreciate any help.

#### Example
![image](https://user-images.githubusercontent.com/69252905/89427728-800f1f00-d733-11ea-92d9-6462011950e6.png)

```python

from lightkurve import KeplerTargetPixelFile
tpf = KeplerTargetPixelFile("https://stdatu.stsci.edu/missions/kepler/target_pixel_files/0086/008644288/kplr008644288-2009131105131_lpd-targ.fits.gz")

tpf.interact()

**Comment by barentsen** [comment]
@eugeneb5 Thank you for using Lightkurve and thank you for getting in touch! :+1:  I'm sorry to hear you are having trouble with the `interact` tool.

The example you posted looks good! The most likely reason for the issue is that the version of Lightkurve you are using is 18 months old (v1.0b25), and there have been a large number of bugfixes since.

Would you be willing to update Lightkurve and try again?  You should be able to do so using the following command:
```
conda update lightkurve
```

Once that's done, you can verify the version that's installed using the following snippet of Python code:
```python
import lightkurve as lk
print(lk.__version__)
```

This should show `v1.11.0` or similar.

Please let me know if this doesn't resolve the issue!

**Comment by eugeneb5** [comment]
Thank you so much @barentsen!
Inputting that cmd into cmd prompt didn't give me the update to 1.11.0 for some reason but doing it via 'pip install -- upgrade' successfully did.  Is now all working!

**Comment by barentsen** [comment]
That's great to hear!  Thanks for reporting back @eugeneb5! :+1:
