### ISSUE TITLE
Lightkurve2 - interact_bls() broken

### ISSUE THREAD

**Issue by orionlee** [KeplerGO/lightkurve#848]
#### Problem description

`interact_bls()` is not yet working in the current `master` (Sep 20, 2020), due to the change of making time, flux from unitless numbers to `Time` / `Quantity`: 

```
ERROR:tornado.application:Uncaught exception GET /autoload.js?bokeh-autoload-element=1001&bokeh-absolute-url=http://localhost:53003&resources=none (::1)
...
site-packages\astropy\time\core.py", line 1734, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'TimeDelta' object has no attribute 'log10'
...
  File "c:\dev\lightkurve\lightkurve\interact_bls.py", line 449, in _create_interact_ui
    period_values = np.logspace(np.log10(minp), np.log10(maxp), npoints_slider.value)
TypeError: loop of ufunc does not support argument 0 of type TimeDelta which has no callable log10 method
```

I fixed a couple of those issues locally (by stripping units) and then stopped. 
Maybe there is a more robust way to deal with it, rather than converting `Quantity` / `Time` back to unitless number upon encountering an error?

#### Environment

-  platform (e.g. Linux, OSX, Windows): Windows
-  lightkurve version (e.g. 1.0b6): `master`, lightkurve2 alpha based
-  installation method (e.g. pip, conda, source): soruce

**Comment by barentsen** [comment]
I believe a long-term goal of AstroPy is to have `Time`/`Quantity` objects workseamlessly with all numpy/scipy functions, but unfortunately that is not the case yet.  This is a problem, in particular, for `Time` objects.

There are a number of issues on this topic over in the AstroPy repo.  I tried to look into it once to see if I could help, but it turned out to be surprisingly complicated.

Until these objects work more seamlessly, I'm afraid our only option is to use the `.value` mechanism to pass unitless numbers fo numpy/scipy functions where necessary.
