### ISSUE TITLE
Struggling to access K2 data from Campaign 15

### ISSUE THREAD

**Issue by StuartLittlefair** [KeplerGO/lightkurve#87]
Should this be accessible yet? i.e, should this work?

```
tpf = KeplerTargetPixelFile.from_archive(249914869, campaign=15)
```

I get

```
WARNING: NoResultsWarning: Query returned no results. [astroquery.mast.core]
---------------------------------------------------------------------------
ArchiveError                              Traceback (most recent call last)
<ipython-input-2-215e0a00620d> in <module>()
----> 1 tpf = KeplerTargetPixelFile.from_archive(249914869, campaign=15)

~/anaconda3/lib/python3.6/site-packages/lightkurve/targetpixelfile.py in from_archive(target, cadence, quarter, month, campaign, **kwargs)
    196                                "".format(len(products), target))
    197         elif len(products) < 1:
--> 198             raise ArchiveError("No Target Pixel File found for {} at MAST.".format(target))
    199         path = download_products(products)[0]
    200         return KeplerTargetPixelFile(path, **kwargs)

ArchiveError: No Target Pixel File found for 249914869 at MAST.
```

**Comment by christinahedges** [comment]
Hi Stuart, unfortunately this is a problem with the MAST Portal not being up to date quite yet because the data is so new. It was discussed in issue #81 and @scfleming believes that it will likely be resolved within a week. For now you can download the data directly yourself through MAST:

https://archive.stsci.edu/k2/data_search/search.php?target=249914869&action=Search&resolver=SIMBAD&radius=3.0&outputformat=HTML_Table&max_records=5001&ordercolumn1=ang_sep&ordercolumn2=sci_ra

**Comment by scfleming** [comment]
Yep, C15 is added to our Portal test server and passed initial testing, show it should be available as soon as it gets pushed to operations, nominally this week.

**Comment by StuartLittlefair** [comment]
Thanks @christinahedges
