### ISSUE TITLE
How to generate PDCSAP light curves from TPF

### ISSUE THREAD

**Issue by gjtucson** [KeplerGO/lightkurve#888]
#### Problem description
I am trying to generate PDCSAP equivalent light curves from a TPF file. I don't see how to do that. Code snippet below shows the difference in light curves between PDCSAP downloaded from the host and a light curve derived using tpf.to_lightcurve()

#### Example
# Demonstration example for getting PDCSAP light curves from TPFs

import lightkurve as lk
from lightkurve import search_lightcurvefile
from lightkurve import search_targetpixelfile

import matplotlib
from matplotlib import pyplot as plt

# Define object and campaign
KIC = 'EPIC 251248559'
campaign = 111

# Download target pixel file
tpf = search_targetpixelfile(KIC,cadence='long',mission='K2',campaign=campaign).download()

# Download light curve - PDCSAP
lc1 = search_lightcurvefile(KIC,cadence='long',mission='K2',campaign=campaign).download()
lc1_pdcsap = lc1.PDCSAP_FLUX.remove_nans().remove_outliers()
lc1_pdcsap.plot()

# Derive light curve from target pixel file
lc2 = tpf.to_lightcurve(method='aperture')

# There is no attribute for PDCSAP in this light curve (lc2)
# So, plot what we can
lc2_clean = lc2.remove_nans().remove_outliers()
lc2_clean.plot()

#### Expected behavior
Expect to have an attribute PDCSAP_FLUX in the lc formed from the TPF so the two plots generated from close snippet look the same.

#### Environment

-  platform: OSX, JupyterLab
-  lightkurve version: 1.11.0
-  installation method: can't remember! it was a while ago.

**Comment by barentsen** [comment]
@gjtucson Thank you for opening an issue!

At this time the `tpf.to_lightcurve()` method only produces very basic Simple Aperture Photometry (SAP), i.e. an aperture photometry light curve to which no systematics removal is applied.

In the near future we should be adding the so-called `CBVCorrector` feature to Lightkurve (cf. #855), which will allow users to apply systematics removal in a way that is very similar to that applied by the "Pre-search Data Conditioning" (PDC) module of the official TESS/Kepler pipelines.

It will likely never be possible to replicate the PDCSAP_FLUX values *exactly*, because the official pipelines are not available to be run by users, however I expect that the `CBVCorrector` will get you very close.

Does that help / answer your question?

**Comment by gjtucson** [comment]
Hi Geert,

Thank you for the response to my issue. I've taken a quick look at the 
CBVcorrector development docs and I agree that it will likely perform 
well for my application. I'll watch for the release.

Cheers,
George
