### ISSUE TITLE
Lightkurve2 tpf.plot_pixels() misc. enhancement

### ISSUE THREAD

**Issue by orionlee** [KeplerGO/lightkurve#894]
#### Problem description
I've been using `Lightkurve2`'s `tpf.plot_pixels()`, and would suggest the following minor enhancement:

1. Include the time range, row /column numbers in the default plot output
2. when using `show_flux=True`, use black dots when the background is light (yellow or green) so that they are easier to spot.
3. ~~add a optional parameter, `pixel_size_inch`, so that~~ users can control the size of the diagram (currently it's hardcoded as 1.5 inch) - it can be done when `plot_pixels()` honors the optional `ax` parameter. The codes currently do not yet honor it.

Example plot with (1) and (2) adopted (from Nora Eisner's LATTE):

![image](https://user-images.githubusercontent.com/250644/97934525-d2f47480-1d2a-11eb-97ac-4df333900473.png)

#### Environment

-  lightkurve version (e.g. 1.0b6): `master` (lightkurve2 beta)

**Comment by barentsen** [comment]
Thanks @orionlee!

/cc @astrobel Do you want to weigh in?

My two cents:

> 1. Include the time range, row /column numbers in the default plot output

Agreed!

> 2. when using show_flux=True, use black dots when the background is light (yellow or green) so that they are easier to spot.

The change you made is no doubt an improvement on the current default.

I wonder if we could use white dots with a black edge, so that the style does not have to change depending on the background. I guess giving the white dots a border could make the plot too busy tho, and may perhaps not solve the issue as effectively as you did here?

> 3. add a optional parameter, pixel_size_inch, so that users can control the size of the diagram (currently it's hardcoded as 1.5 inch)

The `plt.figure()` and `plt.subplots()` functions in matplotlib accept a `figsize` argument, so it would probably be best to adopt that same parameter name.

One caveat is that if we allow `figsize` to be passed to `plot_pixels`, users may expect other matplotlib-based plotting functions in Lightkurve to accept it too (and `dpi` as well).  We could do this modifying the `utils.plot_image()` and `LightCurve._create_plot()` helper functions which I believe power all other plotting methods in `LightCurve` and `TargetPixelFile`, but we'd of course have to update docstrings etc etc.

**Comment by orionlee** [comment]
> The plt.figure() and plt.subplots() functions in matplotlib accept a figsize argument, so it would probably be best to adopt that same parameter name.

Ah, I got tunnel vision and forgot that `plot_pixels()` accept `ax` as an argument. So the need to resize a plot could possibly be met by the following without introducing new options:
```python
ax = plt.figure(figsize=(6, 6)).gca()
tpf_trunc.plot_pixels(ax=ax, show_flux=True);
```

The above code snippets don't quite work with the current codes (the current codes ignore `ax` and do its own thing). But if we agree that it should work, the codes could be adjusted.

**Comment by astrobel** [comment]
Thanks for tagging me @barentsen! I agree that passing `ax` to `plot_pixels()` is a good solution for the figure size, but I also think that in the long run it's worth moving away from the hard-coded figure size, at least by introducing a variable to handle that.

I'm also on board with adding pixel row/col numbers, and a time range. It'll be an easy addition to add the time range to the title; I wonder if it's worth adding a few extra conditional statements to include the quarter/campaign/sector number too?

Regarding the markers, I think it's a good idea to try white-with-black-outline markers first, before committing to the two different colours, though I'm not sure what a good equivalent of that would be for the periodogram plots, where of course there's a line instead of dots...

**Comment by barentsen** [comment]
> forgot that plot_pixels() accepts ax as an argument. So the need to resize a plot could possibly be met by the following without introducing new options:

Agreed!  This already works for other functions, e.g. one can alter `dpi` of a `tpf.plot()` as follows:

```python
ax = plt.figure(dpi=100).gca()
tpf.plot(ax=ax);
```

My preference is to advertise this as the preferred way to alter figure/axis options (because every convenience parameter added to the various plotting methods may result in a bug or maintenance issue down the road).  We can of course make exceptions for parameters that would be used very often, but a convincing example/case has to be made.

**Comment by orionlee** [comment]
I updated the summary (the initial comment) to reflect the agreement.

---

> Agreed! This already works for other functions, e.g. one can alter `dpi` of a `tpf.plot()` as follows:
> 
> ```python
> ax = plt.figure(dpi=100).gca()
> tpf.plot(ax=ax);
> ```

For the purpose of changing plot size, a slight difference when one passes `ax` to plotting methods is that the specified style is not completely applied (See screenshot below for `lc.scatter()`). 

I have not raised the issue because it doesn't bother me, but if we want to advertise it, we probably want to somehow address the discrepancy.

![image](https://user-images.githubusercontent.com/250644/98191087-52ba4480-1ecd-11eb-8d46-7ac3ecbee8f1.png)
