### ISSUE TITLE
HLSP TESS light curves are not found by search_lightcurvefile

### ISSUE THREAD

**Issue by LucaNap** [KeplerGO/lightkurve#912]
The lightkurve search command does not find some TOIs like 980.01, 1187.01, 2173.01... is there a reason why?

Thank you

**Comment by barentsen** [comment]
@LucaNap Thank you for opening this issue.  It would be great for Lightkurve to support all the HLSP light curves!

I believe you are referring to the newly-announced High Level Science Product (HLSP) light curves produced by the MIT Quicklook Pipeline (QLP) and the NASA Ames pipeline (SPOC), is that correct?

These light curves should become accessible via `search_lightcurve` as soon as they are ingested in the MAST Portal. My understanding is that this ingestion process may take a bit more time because of the large data volume.

When I search for e.g. `TOI 980.01` in the Portal right now (i.e. at this url: https://mast.stsci.edu/portal/Mashup/Clients/Mast/Portal.html ) the QLP and SPOC FFI light curves do not show up yet.

Once they have been ingested in the Portal, you should be able to also see them by specifying the `author='all'` keywords as follows:
```python
import lightkurve as lk
lk.search_lightcurve("TOI 980.01", author='all')
```

We may have to add or modify a custom reader function to read these light curves into a LightCurve object.  I'll look into that asap.

(/cc @scfleming)

**Comment by scfleming** [comment]
That's correct, we have ~Sectors 20-26 up so far.  We can do ~1 Sectors per 1-2 days, you can check status of Sectors on the MAST homepages for each in the Data Access sections: http://archive.stsci.edu/hlsp/qlp#section-6971afb5-1e2e-405d-9a6a-d907399ab2e1 and http://archive.stsci.edu/hlsp/tess-spoc#section-d9377b2e-ee1c-405d-b5a9-7672c84720c1.

**Comment by barentsen** [comment]
Thanks for the info and pointers @scfleming!!

Sectors 20-26 are sufficient for me to start adding support for these products!  I opened PR #913 for this purpose.

(It looks like a few minor changes are necessary.)

**Comment by LucaNap** [comment]
You guys are doing an amazing job. Thank you!

**Comment by barentsen** [comment]
Support for accessing the QLP and SPOC FFI light curve products via the `search_lightcurve` function has been added via #913 (see link for examples) and will be part of the upcoming `2.0b4` release.

Many thanks for opening this issue @LucaNap, which triggered this important improvement.  Please open a new issue if you encounter any further problems! :+1:

**Comment by LucaNap** [comment]
Hey @barentsen , do you think Lightkurve should also support other pipelines like DIAMANTE, ELEANOR (etc)? Some TOIs still only have those.

**Comment by barentsen** [comment]
Yep, we should definitely add support for DIAMANTE, PATHOS, CDIPS, and TASOC.  (And ELEANOR once they deliver light curve files to MAST -- for now they have released processed pixel data only.)

Maybe I'll re-open this issue so I don't forget.

**Comment by barentsen** [comment]
For clarity, I opened a separate issue for this with more details, here: #918
