### ISSUE TITLE
Release 2 of lightkurve?

### ISSUE THREAD

**Issue by martindevora** [KeplerGO/lightkurve#937]
Hi this is only a question. When are you planning to release the version 2 of Lightkurve? I see that you are implementing the new cadence methods retrieval (long, short, fast... ) and that would be a very nice feature to have now.

Kind regards.

**Comment by barentsen** [comment]
@martindevora Thanks for asking!  We should be very close to the 2.0.0 release.  The only major outstanding issue is updating the final bits of docs and creating a good summary of all the changes ("What's new in v2.0" etc).  I've been working on that this week and hope to finish soon.

In meanwhile, you can try out v2.0beta5, which was released last week and is very close to what 2.0.0 will look like.  For example, it has support for all the different cadence modes and different pipeline products.  You can install it using:
```
pip install --pre --upgrade lightkurve
```

(Adding the `--pre` flag is key, pip will ignore beta versions otherwise.)

**Comment by martindevora** [comment]
Thanks. I'm using lightkurve as a dependency in my setup file. I'll try to include the beta to see whether pypi can resolve it.
