### ISSUE TITLE
Allow lightkurve's psf fitting priors to be input in image coordinates and/or RA, Dec

### ISSUE THREAD

**Issue by amcody** [KeplerGO/lightkurve#95]
Currently one must input detector column and row, which is proving problematic for stars in crowded superstamp regions (e.g., M67) that go across channel boundaries where the detector coordinates are discontinuous. It would be a lot easier to use the local coordinate system of the TPF to specify star positions (though one would still use the detector coordinates to retrieve the PRF model).

**Comment by gully** [comment]
Currently working on this now with AMC!

**Comment by mirca** [comment]
This is really cool! Which branch are you both working on?

**Comment by gully** [comment]
We are discussing the possibility of adding an option to apply `pos_corr` offsets directly inside the `phot.fit()`.  Currently the sole argument of `phot.fit()` is `tpf_flux`.  AMC and I suggest the following change:
Instead of taking `tpf.flux` as an argument, make it take in `tpf`.  This way, the fitting code will have access to `tpf.poss_corr1` (and 2).  

poss_corr would be used to *shift* the priors left-right and up-down, to maintain the desired prior window in the face of spacecraft-induced motion.  This feature can either be the default, or an opt-in keyword-arg.

**Comment by barentsen** [comment]
Closing this issue because we do not currently have resources to develop PRF photometry features, unfortunately!
